'use client';

import { useState } from 'react';
import { EXAMPLE_PEOPLE, MODE_EMOJI, MODE_COLOR } from '@/constants/examples';

export default function ExamplesPage() {
  const [selectedPerson, setSelectedPerson] = useState<number | null>(null);

  const selectedExample = selectedPerson !== null
    ? EXAMPLE_PEOPLE.find(p => p.id === selectedPerson)
    : null;

  return (
    <main className="min-h-screen bg-fire-gradient relative overflow-hidden">
      {/* Background Watermark */}
      <div
        className="fixed inset-0 z-0 pointer-events-none"
        style={{
          backgroundImage: 'url(/assets/Year-of-Horse-Hero-Image3.jpeg)',
          backgroundSize: '105%',
          backgroundPosition: 'center center',
          backgroundRepeat: 'no-repeat',
          opacity: 0.55,
          filter: 'blur(1px)',
        }}
      />
      <div className="fixed inset-0 z-0 pointer-events-none bg-gradient-to-b from-black/30 via-transparent to-black/40" />

      <div className="relative z-10 max-w-6xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <a href="/" className="text-fire-gold hover:text-yellow-300 text-sm mb-4 inline-block">
            ← Back to Home
          </a>
          <h1 className="text-4xl md:text-5xl font-bold text-fire-gold text-glow-gold mb-4">
            See Examples
          </h1>
          <p className="text-white text-lg max-w-2xl mx-auto">
            Real prophecies generated by the Fire Horse Oracle for people of all 12 Chinese zodiac signs.
          </p>
          <p className="text-gray-400 text-sm mt-2 italic">
            *These are hypothetical examples with fictional names for demonstration purposes.
          </p>
        </div>

        {/* Zodiac Chart */}
        <div className="flex justify-center mb-8">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/assets/zodiac/Fire-Horse-2026-Chart.jpeg"
            alt="Year of the Fire Horse 2026 - All 12 Zodiac Animals"
            className="w-full max-w-2xl rounded-2xl border-2 border-fire-gold/50 shadow-2xl"
          />
        </div>

        {/* Mode Legend */}
        <div className="flex flex-wrap justify-center gap-4 mb-8">
          <div className="flex items-center gap-2 bg-black/60 px-4 py-2 rounded-full">
            <span>🎲</span>
            <span className="text-yellow-400 font-bold">Wealth</span>
            <span className="text-gray-400 text-sm">Lucky Numbers</span>
          </div>
          <div className="flex items-center gap-2 bg-black/60 px-4 py-2 rounded-full">
            <span>⚔️</span>
            <span className="text-red-500 font-bold">Power</span>
            <span className="text-gray-400 text-sm">Strategic Motto</span>
          </div>
          <div className="flex items-center gap-2 bg-black/60 px-4 py-2 rounded-full">
            <span>❤️</span>
            <span className="text-pink-400 font-bold">Love</span>
            <span className="text-gray-400 text-sm">Love Decree</span>
          </div>
          <div className="flex items-center gap-2 bg-black/60 px-4 py-2 rounded-full">
            <span>🛡️</span>
            <span className="text-blue-400 font-bold">Shield</span>
            <span className="text-gray-400 text-sm">Protective Mantra</span>
          </div>
        </div>

        {/* Examples Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
          {EXAMPLE_PEOPLE.map((person) => (
            <div
              key={person.id}
              onClick={() => setSelectedPerson(person.id)}
              className="bg-black/70 border border-fire-gold/30 rounded-2xl p-4 cursor-pointer hover:border-fire-gold hover:scale-105 transition-all duration-300"
            >
              {/* Person Header */}
              <div className="flex items-center gap-3 mb-3">
                {/* Zodiac Icon */}
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/assets/zodiac/${person.zodiac}.jpeg`}
                  alt={person.zodiac}
                  className="w-16 h-16 rounded-full border-2 border-fire-gold/50 object-cover"
                />
                <div className="flex-1">
                  <h3 className="text-fire-gold font-bold text-lg">{person.name}</h3>
                  <p className="text-gray-400 text-sm">
                    {person.element} {person.zodiac.charAt(0).toUpperCase() + person.zodiac.slice(1)} {person.zodiacChinese}
                  </p>
                  <p className="text-gray-500 text-xs">DOB: {person.dob}</p>
                </div>
              </div>

              {/* Mode Badge */}
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">{MODE_EMOJI[person.mode]}</span>
                <span className={`font-bold ${MODE_COLOR[person.mode]}`}>
                  {person.mode.charAt(0).toUpperCase() + person.mode.slice(1)} Mode
                </span>
                <span className="text-gray-500 text-sm">• {person.modeLabel}</span>
              </div>

              {/* Testimonial Preview */}
              <p className="text-white text-sm italic line-clamp-2">
                &quot;{person.testimonial.substring(0, 80)}...&quot;
              </p>

              {/* Click to View */}
              <p className="text-fire-gold text-xs mt-3 text-center">
                Click to view talisman →
              </p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="text-center">
          <a
            href="/"
            className="inline-block bg-gradient-to-r from-yellow-600 via-yellow-500 to-yellow-600
                       text-black font-bold text-xl py-4 px-8 rounded-xl
                       hover:scale-105 active:scale-95 transition-all duration-200
                       shadow-xl shadow-yellow-500/30"
          >
            Get Your Own Prophecy - $8.88
          </a>
        </div>

        {/* Footer */}
        <footer className="text-center text-sm text-white font-bold mt-12">
          <p>
            Strictly for entertainment purposes only. AI-generated artwork.
            <br />
            Not financial, legal, or gambling advice.
          </p>
          <p className="mt-2">© 2026 Red Horse Oracle. 18+.</p>
        </footer>
      </div>

      {/* Modal for viewing talisman */}
      {selectedExample && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/90"
          onClick={() => setSelectedPerson(null)}
        >
          <div
            className="bg-black/95 border-2 border-fire-gold rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto p-6"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              onClick={() => setSelectedPerson(null)}
              className="absolute top-4 right-4 text-gray-400 hover:text-white text-2xl"
            >
              ✕
            </button>

            {/* Person Info */}
            <div className="flex items-center gap-4 mb-4">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`/assets/zodiac/${selectedExample.zodiac}.jpeg`}
                alt={selectedExample.zodiac}
                className="w-20 h-20 rounded-full border-2 border-fire-gold object-cover"
              />
              <div>
                <h2 className="text-fire-gold font-bold text-2xl">{selectedExample.name}</h2>
                <p className="text-white">
                  {selectedExample.element} {selectedExample.zodiac.charAt(0).toUpperCase() + selectedExample.zodiac.slice(1)} {selectedExample.zodiacChinese}
                </p>
                <p className="text-gray-400 text-sm">Born: {selectedExample.dob} (Age {selectedExample.age})</p>
              </div>
            </div>

            {/* Mode Info */}
            <div className="flex items-center gap-2 mb-4 bg-red-950/40 p-3 rounded-xl">
              <span className="text-2xl">{MODE_EMOJI[selectedExample.mode]}</span>
              <div>
                <span className={`font-bold text-lg ${MODE_COLOR[selectedExample.mode]}`}>
                  {selectedExample.mode.charAt(0).toUpperCase() + selectedExample.mode.slice(1)} Mode
                </span>
                <span className="text-gray-400 ml-2">• {selectedExample.modeLabel}</span>
              </div>
            </div>

            {/* Talisman Image */}
            <div className="mb-4">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={selectedExample.talismanImage}
                alt={`${selectedExample.name}'s Fire Horse Talisman`}
                className="w-full rounded-xl border border-fire-gold/50"
                onError={(e) => {
                  (e.target as HTMLImageElement).src = '/assets/zodiac/Fire-Horse-2026-Chart.jpeg';
                }}
              />
            </div>

            {/* Testimonial */}
            <div className="bg-red-950/30 p-4 rounded-xl mb-4">
              <p className="text-white italic text-lg">
                &quot;{selectedExample.testimonial}&quot;
              </p>
              <p className="text-fire-gold text-sm mt-2 text-right">
                — {selectedExample.name}, {selectedExample.zodiac.charAt(0).toUpperCase() + selectedExample.zodiac.slice(1)}
              </p>
            </div>

            {/* Share Link */}
            {selectedExample.revealLink && (
              <div className="bg-black/50 p-3 rounded-xl mb-4">
                <p className="text-gray-400 text-xs mb-1">Share this prophecy:</p>
                <p className="text-fire-gold text-sm break-all">{selectedExample.revealLink}</p>
              </div>
            )}

            {/* CTA */}
            <div className="text-center">
              <a
                href="/"
                className="inline-block bg-fire-gold text-black font-bold py-3 px-6 rounded-xl hover:scale-105 transition-transform"
              >
                Get Your Own Prophecy
              </a>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
