'use client';

import Image from 'next/image';
import {
  ZodiacAnimal,
  ZodiacElement,
  ZODIAC_CHINESE,
  ELEMENT_CHINESE,
  ZODIAC_PROFILES,
  FIRE_HORSE_RELATIONS,
} from '@/constants/zodiac-data';

interface ZodiacSummaryProps {
  zodiacSign: string;
  zodiacElement?: string | null;
}

export default function ZodiacSummary({ zodiacSign, zodiacElement }: ZodiacSummaryProps) {
  // Validate zodiac sign
  const animal = zodiacSign as ZodiacAnimal;
  const element = zodiacElement as ZodiacElement | null;

  const profile = ZODIAC_PROFILES[animal];
  const relation = FIRE_HORSE_RELATIONS[animal];
  const animalChinese = ZODIAC_CHINESE[animal];
  const elementChinese = element ? ELEMENT_CHINESE[element] : '';

  if (!profile || !relation) {
    return null;
  }

  // Get compatibility color
  const getCompatibilityColor = () => {
    switch (relation.compatibility) {
      case 'ally':
        return 'text-green-400';
      case 'special':
        return 'text-fire-gold';
      case 'clash':
        return 'text-red-400';
      default:
        return 'text-gray-400';
    }
  };

  const getCompatibilityBg = () => {
    switch (relation.compatibility) {
      case 'ally':
        return 'bg-green-900/20 border-green-800/50';
      case 'special':
        return 'bg-yellow-900/20 border-yellow-800/50';
      case 'clash':
        return 'bg-red-900/20 border-red-800/50';
      default:
        return 'bg-gray-900/20 border-gray-800/50';
    }
  };

  return (
    <div className="w-full max-w-md mt-8 space-y-6">
      {/* Section Header */}
      <div className="text-center space-y-1">
        <p className="text-gray-500 text-xs uppercase tracking-widest">Powered by Gemini 3 Pro AI</p>
        <h2 className="text-2xl font-bold text-fire-gold text-glow-gold">
          YOUR ZODIAC FORECAST
        </h2>
        <p className="text-red-400 text-sm">Year of the Fire Horse 2026</p>
      </div>

      {/* Zodiac Card */}
      <div className="bg-black/60 backdrop-blur-sm border border-fire-gold/30 rounded-2xl p-6 space-y-5">
        {/* Animal Image and Title */}
        <div className="flex items-center gap-4">
          <div className="relative w-20 h-20 rounded-full overflow-hidden border-2 border-fire-gold shadow-lg">
            <Image
              src={`/assets/zodiac/${animal.toLowerCase()}.jpeg`}
              alt={`${animal} zodiac`}
              fill
              className="object-cover"
            />
          </div>
          <div>
            <h3 className="text-xl font-bold text-fire-gold">
              {element ? `${element} ${animal}` : animal}
            </h3>
            <p className="text-2xl text-red-300">
              {elementChinese}{animalChinese}
            </p>
            <p className={`text-sm ${getCompatibilityColor()}`}>
              {relation.relation}
            </p>
          </div>
        </div>

        {/* Strengths */}
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">Core Strengths</p>
          <div className="flex flex-wrap gap-2">
            {profile.strengths.map((strength) => (
              <span
                key={strength}
                className="bg-fire-gold/10 border border-fire-gold/30 text-fire-gold text-xs px-3 py-1 rounded-full"
              >
                {strength}
              </span>
            ))}
          </div>
        </div>

        {/* Characteristics */}
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">Characteristics</p>
          <p className="text-gray-300 text-sm leading-relaxed">
            {profile.characteristics}
          </p>
        </div>

        {/* 2026 Forecast */}
        <div className={`${getCompatibilityBg()} border rounded-xl p-4`}>
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">
            2026 Fire Horse Forecast
          </p>
          <p className="text-gray-200 text-sm leading-relaxed">
            {profile.forecast2026}
          </p>
        </div>

        {/* Fire Horse Wisdom */}
        <div className="border-t border-fire-gold/20 pt-4">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">Oracle Wisdom</p>
          <p className="text-fire-gold text-sm italic">
            &quot;{relation.advice}&quot;
          </p>
        </div>
      </div>

      {/* Privacy Notice */}
      <div className="bg-black/40 border border-gray-800 rounded-xl p-4 text-center space-y-2">
        <p className="text-fire-gold text-xs font-bold uppercase tracking-wider">
          Privacy by Design
        </p>
        <p className="text-gray-400 text-xs leading-relaxed">
          Your personalized Fire Horse Oracle was generated by authentic <span className="text-fire-gold">Gemini 3 Pro AI</span>.
          No personal information (names, dates, or identifiers) is stored, retained, or displayed.
          Your reading is based solely on your Chinese zodiac sign.
        </p>
        <p className="text-gray-500 text-xs italic">
          The only worldwide app delivering complete privacy with AI-powered Chinese zodiac forecasts.
        </p>
      </div>
    </div>
  );
}
