export const PRODUCT_MODES = {
  wealth: {
    id: 'wealth',
    name: 'Wealth Mode',
    emoji: '🎲',
    tagline: 'The Gambler',
    description: '6 Personal Lucky Numbers (01-99)',
    fullDescription: 'Receive 6 mystical lucky numbers based on your Chinese zodiac, perfect for lottery, gambling, or important decisions.',
    hook: 'Beat the House',
    visualTheme: 'Golden Fire Horse surrounded by falling coins, treasure chests, gold ingots, and lottery balls with numbers',
    textPrompt: 'Generate exactly 6 lucky numbers between 01-99 in format XX-XX-XX-XX-XX-XX',
    outputFormat: 'numbers',
    example: '08-18-28-38-48-88',
  },
  power: {
    id: 'power',
    name: 'Power Mode',
    emoji: '⚔️',
    tagline: 'The Mogul',
    description: '3-Word Strategic Battle Motto',
    fullDescription: 'Receive a powerful 3-word Sun Tzu style motto to guide your business, career, and conquest in 2026.',
    hook: 'Dominate the Market',
    visualTheme: 'Fire Horse as a war general scaling a mountain peak with lightning, storm clouds, armor, and a golden crown',
    textPrompt: 'Generate a 3-word aggressive strategic motto like "STRIKE THE NORTH" or "CONQUER THEN REST"',
    outputFormat: 'motto',
    example: 'STRIKE THE NORTH',
  },
  love: {
    id: 'love',
    name: 'Love Mode',
    emoji: '❤️',
    tagline: 'The Romantic',
    description: '4-Word Relationship Destiny Decree',
    fullDescription: 'Receive a 4-word romantic destiny phrase to guide your heart, relationships, and love life in 2026.',
    hook: 'Secure the Heart',
    visualTheme: 'Fire Horse and Phoenix dancing together in the sky with hearts, red ribbons, roses, and romantic moonlight',
    textPrompt: 'Generate a 4-word romantic destiny phrase like "LOVE FINDS YOU WORTHY" or "HEARTS UNITE IN FIRE"',
    outputFormat: 'phrase',
    example: 'LOVE FINDS YOU WORTHY',
  },
  shield: {
    id: 'shield',
    name: 'Shield Mode',
    emoji: '🛡️',
    tagline: 'The Guardian',
    description: '3-Word Protective Sacred Mantra',
    fullDescription: 'Receive a 3-word protective mantra to shield you from harm, negativity, and chaos in 2026.',
    hook: 'Survive the Chaos',
    visualTheme: 'Fire Horse standing guard in an ancient temple with protective golden aura, incense smoke, and sacred symbols',
    textPrompt: 'Generate a 3-word protective mantra like "FIRE SHIELDS ME" or "CHAOS CANNOT ENTER"',
    outputFormat: 'mantra',
    example: 'FIRE SHIELDS ME',
  },
} as const;

export type FocusMode = keyof typeof PRODUCT_MODES;
