-- Migration: Create party_questions table and insert all 400 questions
-- Run this in Supabase SQL Editor
-- Generated: 2026-02-01T09:36:45.599Z

-- Drop existing table if needed (uncomment if you want to reset)
-- DROP TABLE IF EXISTS party_questions;

-- Create the party_questions table
CREATE TABLE IF NOT EXISTS party_questions (
  id INTEGER PRIMARY KEY,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  question TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_answer TEXT NOT NULL,
  explanation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_party_questions_category ON party_questions(category);
CREATE INDEX IF NOT EXISTS idx_party_questions_difficulty ON party_questions(difficulty);

-- Enable RLS but allow public read access
ALTER TABLE party_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to questions" ON party_questions;
CREATE POLICY "Allow public read access to questions"
  ON party_questions FOR SELECT
  USING (true);

-- Clear existing questions (if re-running)
TRUNCATE TABLE party_questions;

-- Insert all 400 questions

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(1, 'Fire Horse & Great Race', 'easy', 'What is the specific element for the Horse in 2026?', 'Water', 'Wood', 'Fire', 'Earth', 'Fire', '2026 is the Year of the Fire Horse (Bing Wu).'),
(2, 'Fire Horse & Great Race', 'medium', 'In the Great Race, why did the Horse finish 7th instead of 6th?', 'It fell', 'A snake scared it', 'It stopped to eat', 'It got lost', 'A snake scared it', NULL),
(3, 'Fire Horse & Great Race', 'easy', 'Which of these years was the previous Year of the Fire Horse?', '1966', '1976', '1986', '1996', '1966', NULL),
(4, 'Fire Horse & Great Race', 'medium', 'What is the "Fixed Element" of the Horse (regardless of the year)?', 'Metal', 'Water', 'Fire', 'Wood', 'Fire', NULL),
(5, 'Fire Horse & Great Race', 'medium', 'What time of day is associated with the Horse in the Chinese 24-hour cycle?', '7am-9am', '11am-1pm', '5pm-7pm', '11pm-1am', '11am-1pm', NULL),
(6, 'Fire Horse & Great Race', 'easy', 'Which lucky direction should the Horse face in 2026?', 'North', 'South', 'East', 'West', 'South', NULL),
(7, 'Fire Horse & Great Race', 'medium', 'The Horse is a "Yang" sign. What does "Yang" represent?', 'Passive/Cold', 'Active/Hot', 'Earth/Moon', 'Water/Soft', 'Active/Hot', NULL),
(8, 'Fire Horse & Great Race', 'hard', 'Which of these animals is the Horse''s "Secret Friend"?', 'Rat', 'Tiger', 'Sheep', 'Monkey', 'Sheep', NULL),
(9, 'Fire Horse & Great Race', 'easy', 'People born in the Year of the Horse are said to be most compatible with whom?', 'Rat', 'Tiger', 'Rabbit', 'Ox', 'Tiger', NULL),
(10, 'Fire Horse & Great Race', 'medium', 'Which animal is the "Enemy" or "Clash" sign for the Horse?', 'Snake', 'Rat', 'Dog', 'Dragon', 'Rat', NULL),
(11, 'Fire Horse & Great Race', 'medium', 'What is the lucky flower for the Year of the Horse?', 'Rose', 'Lily', 'Jasmine', 'Sunflower', 'Jasmine', NULL),
(12, 'Fire Horse & Great Race', 'hard', 'Which number is considered UNLUCKY for the Horse?', '1', '2', '3', '7', '1', NULL),
(13, 'Fire Horse & Great Race', 'medium', 'How many years are in a full cycle of the Chinese Zodiac (all signs + all elements)?', '12', '24', '60', '100', '60', NULL),
(14, 'Fire Horse & Great Race', 'hard', 'The Fire Horse is known as the "Horse in the..."?', 'Stable', 'Clouds', 'Army', 'Wild', 'Clouds', NULL),
(15, 'Fire Horse & Great Race', 'medium', 'Which color should a Horse avoid wearing in 2026?', 'Red', 'White', 'Gold', 'Blue', 'Blue', NULL),
(16, 'Fire Horse & Great Race', 'medium', 'In mythology, the Horse is often associated with which celestial body?', 'The Moon', 'The Sun', 'Mars', 'Jupiter', 'The Sun', NULL),
(17, 'Fire Horse & Great Race', 'easy', 'How many "Earthly Branches" are there in the Zodiac?', '5', '10', '12', '14', '12', NULL),
(18, 'Fire Horse & Great Race', 'easy', 'Which season is the Horse associated with?', 'Spring', 'Summer', 'Autumn', 'Winter', 'Summer', NULL),
(19, 'Fire Horse & Great Race', 'medium', 'What kind of personality is a "Fire Horse" specifically known for?', 'Quiet/Shy', 'Stubborn/Passionate', 'Lazy/Calm', 'Scientific/Cold', 'Stubborn/Passionate', NULL),
(20, 'Fire Horse & Great Race', 'easy', 'What is the Horse''s position in the 12-year cycle?', '4th', '6th', '7th', '9th', '7th', NULL),
(21, 'Fire Horse & Great Race', 'medium', 'Which of these is a lucky color for the Horse in 2026?', 'Green', 'Black', 'Purple', 'Silver', 'Purple', NULL),
(22, 'Fire Horse & Great Race', 'medium', 'In the "Great Race," which animal did the Horse run alongside?', 'Sheep', 'Dog', 'Snake', 'Tiger', 'Snake', NULL),
(23, 'Fire Horse & Great Race', 'medium', 'The Horse belongs to which "Compatibility Triangle"?', 'Rat/Dragon/Monkey', 'Tiger/Horse/Dog', 'Ox/Snake/Rooster', 'Rabbit/Sheep/Pig', 'Tiger/Horse/Dog', NULL),
(24, 'Fire Horse & Great Race', 'hard', 'Which of these famous people was a Fire Horse (1966)?', 'Gordon Ramsay', 'Barack Obama', 'Elon Musk', 'Taylor Swift', 'Gordon Ramsay', NULL),
(25, 'Fire Horse & Great Race', 'hard', 'What "Trigram" is associated with the Horse?', 'Water', 'Mountain', 'Fire', 'Thunder', 'Fire', NULL),
(26, 'CNY Traditions & Food', 'easy', 'What is the traditional "New Year''s Eve" dinner called?', 'The Breakfast', 'The Reunion Dinner', 'The Fire Feast', 'The Sweet Meal', 'The Reunion Dinner', NULL),
(27, 'CNY Traditions & Food', 'medium', 'Why are dumplings eaten during CNY?', 'They look like gold ingots', 'They represent clouds', 'They are easy to make', 'They taste like luck', 'They look like gold ingots', NULL),
(28, 'CNY Traditions & Food', 'easy', 'What should you NOT do on the first day of CNY?', 'Eat', 'Sweep the floor', 'Wear red', 'Talk', 'Sweep the floor', NULL),
(29, 'CNY Traditions & Food', 'medium', 'What does the word "Nian" (New Year) actually mean in Chinese mythology?', 'A star', 'A monster', 'A king', 'A gift', 'A monster', NULL),
(30, 'CNY Traditions & Food', 'easy', 'Why is red the primary color of CNY?', 'It represents the sun', 'It scares away monsters', 'It was the Emperor''s favorite', 'It is cheap to buy', 'It scares away monsters', NULL),
(31, 'CNY Traditions & Food', 'easy', 'What is "Hongbao"?', 'A soup', 'A red envelope with money', 'A type of horse', 'A firework', 'A red envelope with money', NULL),
(32, 'CNY Traditions & Food', 'easy', 'Which fruit is given to represent "Wealth" and "Luck"?', 'Apples', 'Grapes', 'Mandarins', 'Bananas', 'Mandarins', NULL),
(33, 'CNY Traditions & Food', 'medium', 'What is the final day of the CNY celebrations called?', 'The Dragon Day', 'The Moon Party', 'The Lantern Festival', 'The Great End', 'The Lantern Festival', NULL),
(34, 'CNY Traditions & Food', 'hard', 'On which day of the Lunar New Year do "Fire Horses" celebrate their "Ben Ming Nian" (Zodiac Year)?', 'Day 1', 'Day 15', 'Every day', 'The last day', 'Day 1', NULL),
(35, 'CNY Traditions & Food', 'medium', 'What sticky cake is eaten to "climb higher" in the new year?', 'Mooncake', 'Niangao', 'Baozi', 'Dim Sum', 'Niangao', NULL),
(36, 'CNY Traditions & Food', 'easy', 'Which animal comes AFTER the Horse in the Zodiac?', 'Monkey', 'Goat/Sheep', 'Dog', 'Rooster', 'Goat/Sheep', NULL),
(37, 'CNY Traditions & Food', 'easy', 'How many days does the traditional CNY celebration last?', '3 days', '7 days', '15 days', '30 days', '15 days', NULL),
(38, 'CNY Traditions & Food', 'easy', 'Why are firecrackers set off during the New Year?', 'To wake up the Horse', 'To scare evil spirits', 'To signal dinner', 'To light the way', 'To scare evil spirits', NULL),
(39, 'CNY Traditions & Food', 'medium', 'What does a "fish" dish represent in a CNY meal?', 'Speed', 'Surplus/Extra', 'Wisdom', 'Peace', 'Surplus/Extra', NULL),
(40, 'CNY Traditions & Food', 'medium', 'Which of these is considered bad luck to give as a gift?', 'Fruit', 'Tea', 'A Clock', 'Red Envelopes', 'A Clock', NULL),
(41, 'CNY Traditions & Food', 'hard', 'What is the "Zodiac Gate" that the Horse had to pass in the race?', 'The Jade Gate', 'The Heavenly Gate', 'The Southern Gate', 'The Fire Gate', 'The Heavenly Gate', NULL),
(42, 'CNY Traditions & Food', 'easy', 'People born in the Year of the Horse are often described as...', 'Free-spirited', 'Calculating', 'Home-bodies', 'Silent', 'Free-spirited', NULL),
(43, 'CNY Traditions & Food', 'hard', 'In 2026, which element "Feeds" the Fire of the Horse?', 'Water', 'Metal', 'Wood', 'Earth', 'Wood', NULL),
(44, 'CNY Traditions & Food', 'medium', 'Which body part is traditionally associated with the Horse sign?', 'The Heart', 'The Liver', 'The Lungs', 'The Eyes', 'The Heart', NULL),
(45, 'CNY Traditions & Food', 'medium', 'What is the "Lucky Stone" for those born in the Year of the Horse?', 'Diamond', 'Topaz', 'Ruby', 'Pearl', 'Topaz', NULL),
(46, 'CNY Traditions & Food', 'medium', 'During CNY, what do you hang on doors to bring luck?', 'Red Banners (Couplets)', 'Silver bells', 'Horse shoes', 'Green leaves', 'Red Banners (Couplets)', NULL),
(47, 'CNY Traditions & Food', 'hard', 'Which mythical creature is the "best friend" of the Horse?', 'The Phoenix', 'The Dragon', 'The Qilin', 'The Pixiu', 'The Qilin', NULL),
(48, 'CNY Traditions & Food', 'medium', 'What is the Horse''s "Lucky Metal"?', 'Gold', 'Silver', 'Bronze', 'Iron', 'Gold', NULL),
(49, 'CNY Traditions & Food', 'hard', 'When the Horse is stressed, what is its traditional "healing" element?', 'Drinking Water', 'Walking in Forest', 'Sitting by Fire', 'Digging in Earth', 'Drinking Water', NULL),
(50, 'CNY Traditions & Food', 'easy', 'In 2026, the New Year falls on which date?', 'Jan 21', 'Feb 17', 'Mar 1', 'Feb 5', 'Feb 17', NULL);

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(51, 'History, Art & Horse Lore', 'hard', 'Which famous Chinese painting features 100 horses in various poses?', 'The Night Revels', 'One Hundred Horses', 'The Silk Road', 'The Jade Steed', 'One Hundred Horses', NULL),
(52, 'History, Art & Horse Lore', 'medium', 'In Chinese history, "Heavenly Horses" were sought from Central Asia for what?', 'Racing', 'Farming', 'War & Speed', 'Food', 'War & Speed', NULL),
(53, 'History, Art & Horse Lore', 'medium', 'Which dynasty is famous for its "Tri-color" (Sancai) glazed pottery horses?', 'Han', 'Tang', 'Ming', 'Qing', 'Tang', NULL),
(54, 'History, Art & Horse Lore', 'hard', 'The "Bronze Galloping Horse" (Ma Chao Long) shows a horse treading on what?', 'A Snake', 'A Cloud', 'A Flying Swallow', 'Water', 'A Flying Swallow', NULL),
(55, 'History, Art & Horse Lore', 'medium', 'Which 1966 Fire Horse is a famous boxing champion?', 'Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Evander Holyfield', 'Mike Tyson', NULL),
(56, 'History, Art & Horse Lore', 'hard', 'In the "Six Steeds of Zhao Ling," the horses belong to which Emperor?', 'Qin Shi Huang', 'Taizong', 'Wu Zetian', 'Kangxi', 'Taizong', NULL),
(57, 'History, Art & Horse Lore', 'medium', 'What does the phrase "Ma Dao Cheng Gong" mean?', 'Wait for the Horse', 'Success upon the horse''s arrival', 'The horse is tired', 'Horse racing is fun', 'Success upon the horse''s arrival', NULL),
(58, 'History, Art & Horse Lore', 'medium', 'In Chinese chess (Xiangqi), how does the Horse (Ma) move?', 'Straight', 'Diagonally', '"L" shape with a limp', 'Randomly', '"L" shape with a limp', NULL),
(59, 'History, Art & Horse Lore', 'medium', 'Which of these is a famous "Horse" landmark in Scotland?', 'The Kelpies', 'The Centaur', 'The Pony Bridge', 'The White Horse', 'The Kelpies', NULL),
(60, 'History, Art & Horse Lore', 'hard', 'In Western Astrology, which sign is the closest equivalent to the Chinese Horse?', 'Aries', 'Gemini', 'Leo', 'Sagittarius', 'Gemini', NULL),
(61, 'History, Art & Horse Lore', 'hard', 'In the 2026 "Fire Horse" year, which "Heavenly Stem" is paired with the Horse?', 'Jia', 'Yi', 'Bing', 'Ding', 'Bing', NULL),
(62, 'History, Art & Horse Lore', 'hard', 'The Horse is the only animal in the Zodiac that represents which "Trigram"?', 'Li (Fire)', 'Kan (Water)', 'Zhen (Thunder)', 'Xun (Wind)', 'Li (Fire)', NULL),
(63, 'History, Art & Horse Lore', 'medium', 'In 2026, the "Tai Sui" (Grand Duke Jupiter) is located in which direction?', 'North', 'South', 'East', 'West', 'South', NULL),
(64, 'History, Art & Horse Lore', 'hard', 'What is the traditional Chinese name for the Horse in the Zodiac?', 'Zi', 'Chou', 'Wu', 'Wei', 'Wu', NULL),
(65, 'History, Art & Horse Lore', 'medium', 'If you are a Horse, 2026 is your "Ben Ming Nian." What is traditionally worn for protection?', 'Green hats', 'Red underwear/socks', 'Blue shoes', 'Gold glasses', 'Red underwear/socks', NULL),
(66, 'History, Art & Horse Lore', 'medium', 'The Fire Horse is said to have the most energy. Which element "controls" or weakens this Fire?', 'Wood', 'Earth', 'Water', 'Metal', 'Water', NULL),
(67, 'History, Art & Horse Lore', 'medium', 'Which Chinese General is famous for his "Red Hare" horse?', 'Zhuge Liang', 'Guan Yu', 'Cao Cao', 'Sun Tzu', 'Guan Yu', NULL),
(68, 'History, Art & Horse Lore', 'medium', 'What is the "Hour of the Horse" in standard time?', '9pm-11pm', '11am-1pm', '3am-5am', '1pm-3pm', '11am-1pm', NULL),
(69, 'History, Art & Horse Lore', 'easy', 'How many years apart are two "Fire Horse" years?', '12', '24', '60', '120', '60', NULL),
(70, 'History, Art & Horse Lore', 'easy', 'Which of these is NOT a personality trait of a Horse?', 'Patience', 'Independence', 'High Spirit', 'Charisma', 'Patience', NULL),
(71, 'History, Art & Horse Lore', 'hard', 'In 2026, which zodiac sign is "Indirectly Clashing" with the Horse?', 'Ox', 'Rabbit', 'Dragon', 'Rooster', 'Rabbit', NULL),
(72, 'History, Art & Horse Lore', 'hard', 'The "Wooden Horse" of Troy is from Greek myth, but what is the Chinese "Wooden Horse" (Muniu Liuma)?', 'A toy', 'A mechanical supply wagon', 'A statue', 'A boat', 'A mechanical supply wagon', NULL),
(73, 'History, Art & Horse Lore', 'medium', 'What is the "Lucky Month" for Horses in 2026?', 'January', 'June', 'October', 'December', 'June', NULL),
(74, 'History, Art & Horse Lore', 'hard', 'Which direction is "The Horse''s Position" on a traditional Luopan compass?', '0 degrees', '90 degrees', '180 degrees', '270 degrees', '180 degrees', NULL),
(75, 'History, Art & Horse Lore', 'hard', 'What is the "Horse''s Flower" in Feng Shui?', 'Lotus', 'Peach Blossom', 'Calla Lily', 'Orchid', 'Peach Blossom', NULL),
(76, '2026 Astronomy & Traditions', 'medium', '2026 is the year of the "Bing Wu." What color does "Bing" (Fire) represent?', 'Yellow', 'Red', 'White', 'Black', 'Red', NULL),
(77, '2026 Astronomy & Traditions', 'hard', 'What major astronomical event happens in August 2026?', 'Total Solar Eclipse', 'Mars Landing', 'Comet Halley', 'Lunar Collision', 'Total Solar Eclipse', NULL),
(78, '2026 Astronomy & Traditions', 'medium', 'The 2026 CNY starts on Feb 17. Is this considered "Early" or "Late" compared to most years?', 'Very Early', 'Average', 'Late', 'Very Late', 'Late', NULL),
(79, '2026 Astronomy & Traditions', 'hard', 'Which "Flying Star" is in the Center of the home in 2026?', 'Star 1', 'Star 3', 'Star 5', 'Star 9', 'Star 3', NULL),
(80, '2026 Astronomy & Traditions', 'medium', 'In the "Five Elements" theory, Fire creates what?', 'Water', 'Metal', 'Earth', 'Wood', 'Earth', NULL),
(81, '2026 Astronomy & Traditions', 'medium', 'Which "Celestial Animal" protects the South (The Horse''s home)?', 'The Black Tortoise', 'The Red Phoenix', 'The White Tiger', 'The Green Dragon', 'The Red Phoenix', NULL),
(82, '2026 Astronomy & Traditions', 'hard', 'What is a "Lichun" in the Chinese calendar?', 'The Solar Start of Spring', 'A type of tea', 'A horse''s mane', 'The New Year''s Eve', 'The Solar Start of Spring', NULL),
(83, '2026 Astronomy & Traditions', 'easy', 'If 2026 is the Fire Horse, what was 2025?', 'Wood Snake', 'Fire Snake', 'Earth Snake', 'Metal Snake', 'Wood Snake', NULL),
(84, '2026 Astronomy & Traditions', 'easy', 'What will 2027 be?', 'Fire Sheep', 'Earth Sheep', 'Water Sheep', 'Metal Sheep', 'Fire Sheep', NULL),
(85, '2026 Astronomy & Traditions', 'medium', 'How many months are in the Lunar Year of 2026?', '12', '13', '11', '10', '12', NULL),
(86, '2026 Astronomy & Traditions', 'medium', 'What is the "Spirit of the Horse" often compared to in Chinese idioms?', 'Dragon-Horse Spirit', 'Tiger-Horse Power', 'Snake-Horse Speed', 'Dog-Horse Loyalty', 'Dragon-Horse Spirit', NULL),
(87, '2026 Astronomy & Traditions', 'medium', 'Which "Body Element" should a Fire Horse watch in 2026?', 'Digestion', 'Heart/Circulation', 'Lungs', 'Bones', 'Heart/Circulation', NULL),
(88, '2026 Astronomy & Traditions', 'easy', 'Why do people buy new clothes for CNY 2026?', 'To look cool', 'To signal a fresh start', 'To spend money', 'Because it''s a rule', 'To signal a fresh start', NULL),
(89, '2026 Astronomy & Traditions', 'medium', 'What is the "Horse''s Gift" to the world?', 'Silence', 'Freedom', 'Order', 'Peace', 'Freedom', NULL),
(90, '2026 Astronomy & Traditions', 'medium', 'On which day of CNY do people traditionally "Visit the In-laws"?', 'Day 1', 'Day 2', 'Day 5', 'Day 15', 'Day 2', NULL),
(91, '2026 Astronomy & Traditions', 'easy', 'What is "Jiaozi"?', 'A horse breed', 'Dumplings', 'A firework', 'A red robe', 'Dumplings', NULL),
(92, '2026 Astronomy & Traditions', 'hard', 'The Horse belongs to which "Trine"?', 'First', 'Second', 'Third', 'Fourth', 'Third', NULL),
(93, '2026 Astronomy & Traditions', 'medium', 'Which of these is a "Lucky Food" specifically for the Horse?', 'Carrots/Vegetables', 'Meat', 'Fish', 'Cake', 'Carrots/Vegetables', NULL),
(94, '2026 Astronomy & Traditions', 'medium', 'What should you avoid "cutting" during the CNY period?', 'Paper', 'Hair', 'Vegetables', 'Cake', 'Hair', NULL),
(95, '2026 Astronomy & Traditions', 'hard', 'The Fire Horse is often called the "Horse of the..."?', 'Sun', 'Sky', 'Forest', 'Road', 'Road', NULL),
(96, '2026 Astronomy & Traditions', 'medium', 'In 2026, which zodiac sign is the "Helper" of the Horse?', 'Dog', 'Pig', 'Monkey', 'Snake', 'Dog', NULL),
(97, '2026 Astronomy & Traditions', 'medium', 'What is the "Lucky Number" for 2026?', '4', '8', '9', '0', '9', NULL),
(98, '2026 Astronomy & Traditions', 'medium', 'Which of these is a "Fire Horse" year?', '1906', '1936', '1966', 'All of the above', 'All of the above', NULL),
(99, '2026 Astronomy & Traditions', 'easy', 'What is the "Smallest" horse in the zodiac race?', 'The Pony', 'The Horse is just one size', 'The Yearling', 'The Foal', 'The Horse is just one size', NULL),
(100, '2026 Astronomy & Traditions', 'easy', 'What is the best way for a Horse to ensure luck in 2026?', 'Stay home', 'Keep moving/Active', 'Sleep more', 'Change jobs', 'Keep moving/Active', NULL);

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(101, 'Modern Culture & Global Horses', 'medium', 'Which 1966 "Fire Horse" actress played a spy''s love interest and an X-Men mutant?', 'Halle Berry', 'Nicole Kidman', 'Sophie Marceau', 'Robin Wright', 'Halle Berry', NULL),
(102, 'Modern Culture & Global Horses', 'easy', 'In the movie Toy Story, what is the name of Woody''s loyal horse?', 'Buster', 'Bullseye', 'Bandit', 'Buttercup', 'Bullseye', NULL),
(103, 'Modern Culture & Global Horses', 'easy', 'Which luxury car brand features a "Prancing Horse" as its logo?', 'Porsche', 'Lamborghini', 'Ferrari', 'Mustang', 'Ferrari', NULL),
(104, 'Modern Culture & Global Horses', 'medium', 'In the Harry Potter series, what half-horse, half-eagle creature does Harry ride?', 'Thestral', 'Centaur', 'Hippogriff', 'Pegasus', 'Hippogriff', NULL),
(105, 'Modern Culture & Global Horses', 'easy', 'Which U.S. state is known as the "Horse Capital of the World"?', 'Texas', 'Kentucky', 'Montana', 'Florida', 'Kentucky', NULL),
(106, 'Modern Culture & Global Horses', 'hard', 'In the "Year of the Horse," which famous tech entrepreneur (born 1954 - Wood Horse) co-founded Apple?', 'Steve Jobs', 'Bill Gates', 'Steve Wozniak', 'Tim Cook', 'Steve Wozniak', NULL),
(107, 'Modern Culture & Global Horses', 'easy', 'What is the name of the winged horse in Greek Mythology?', 'Hercules', 'Pegasus', 'Arion', 'Sleipnir', 'Pegasus', NULL),
(108, 'Modern Culture & Global Horses', 'medium', 'Which famous 1966 "Fire Horse" actor starred in Happy Gilmore?', 'Adam Sandler', 'Ben Stiller', 'Jim Carrey', 'Will Ferrell', 'Adam Sandler', NULL),
(109, 'Modern Culture & Global Horses', 'medium', 'In the Disney movie Mulan, what is the name of her black horse?', 'Maximus', 'Khan', 'Angus', 'Philippe', 'Khan', NULL),
(110, 'Modern Culture & Global Horses', 'medium', 'Which country is home to the wild "Przewalski''s Horse"?', 'Russia', 'Mongolia', 'China', 'Kazakhstan', 'Mongolia', NULL),
(111, 'Modern Culture & Global Horses', 'medium', 'What is the term for a female horse under the age of four?', 'Colt', 'Filly', 'Mare', 'Foal', 'Filly', NULL),
(112, 'Modern Culture & Global Horses', 'hard', 'Which of these "Horse" movies won the Oscar for Best Picture?', 'War Horse', 'Secretariat', 'Seabiscuit', 'None of these', 'None of these', NULL),
(113, 'Modern Culture & Global Horses', 'medium', 'In chess, how many squares does a Knight (Horse) move in total for one "L" jump?', '2', '3', '4', '5', '3', NULL),
(114, 'Modern Culture & Global Horses', 'hard', 'Which famous 1966 "Fire Horse" is the "Queen of Latin Pop"?', 'Shakira', 'Jennifer Lopez', 'Martha Sanchez', 'Paulina Rubio', 'Paulina Rubio', NULL),
(115, 'Modern Culture & Global Horses', 'medium', 'What is the tallest breed of horse in the world?', 'Shire', 'Clydesdale', 'Percheron', 'Arabian', 'Shire', NULL),
(116, 'Modern Culture & Global Horses', 'medium', 'In the Lord of the Rings, what is the name of Gandalf''s horse?', 'Shadowfax', 'Bill', 'Arod', 'Hasufel', 'Shadowfax', NULL),
(117, 'Modern Culture & Global Horses', 'medium', 'Which Olympic sport is the only one where men and women compete directly against each other?', 'Tennis', 'Equestrian', 'Fencing', 'Sailing', 'Equestrian', NULL),
(118, 'Modern Culture & Global Horses', 'easy', 'What does it mean if a horse has its ears pinned back?', 'It is happy', 'It is listening', 'It is angry/upset', 'It is sleepy', 'It is angry/upset', NULL),
(119, 'Modern Culture & Global Horses', 'medium', 'Which 1966 "Fire Horse" directed the film Iron Man?', 'Jon Favreau', 'James Gunn', 'Joss Whedon', 'Zack Snyder', 'Jon Favreau', NULL),
(120, 'Modern Culture & Global Horses', 'hard', 'What is the "Horse Latitudes" a geographic term for?', 'A racing track', 'Subtropical high-pressure belts', 'A mountain range', 'A desert', 'Subtropical high-pressure belts', NULL),
(121, 'Modern Culture & Global Horses', 'medium', 'In Norse mythology, Odin''s horse Sleipnir had how many legs?', '4', '6', '8', '12', '8', NULL),
(122, 'Modern Culture & Global Horses', 'easy', 'Which of these is a "Horse" idiom meaning to hear news directly from the source?', 'Straight from the horse''s mouth', 'Hold your horses', 'Dark horse', 'One-horse town', 'Straight from the horse''s mouth', NULL),
(123, 'Modern Culture & Global Horses', 'hard', 'What is the "Year of the Fire Horse" often associated with in Japanese culture?', 'Great Harvest', 'High Birth Rates', 'Low Birth Rates', 'Solar Eclipses', 'Low Birth Rates', NULL),
(124, 'Modern Culture & Global Horses', 'hard', 'Which artist painted the famous "Blue Horse" (Der Blaue Reiter)?', 'Picasso', 'Franz Marc', 'Van Gogh', 'Dali', 'Franz Marc', NULL),
(125, 'Modern Culture & Global Horses', 'medium', 'In the Chinese Zodiac, which sign is the "Secret Ally" of the Horse?', 'The Dog', 'The Tiger', 'The Sheep', 'The Pig', 'The Sheep', NULL),
(126, 'Logic, Math & Zodiac Riddles', 'easy', 'If a Fire Horse is born every 60 years, and the last was 1966, what year comes after 2026?', '2076', '2086', '2106', '2126', '2086', NULL),
(127, 'Logic, Math & Zodiac Riddles', 'easy', 'How many total animals are in the Chinese Zodiac?', '10', '12', '14', '16', '12', NULL),
(128, 'Logic, Math & Zodiac Riddles', 'medium', 'If you are born in 2026, how old will you be during the next Year of the Horse?', '10', '11', '12', '13', '12', NULL),
(129, 'Logic, Math & Zodiac Riddles', 'hard', 'Which element is "absent" from 2026 (Fire Horse)?', 'Fire', 'Wood', 'Metal', 'Water', 'Metal', NULL),
(130, 'Logic, Math & Zodiac Riddles', 'medium', 'A Horse is running East. The wind is blowing West. Which way does the Horse''s mane fly?', 'East', 'West', 'North', 'South', 'West', NULL),
(131, 'Logic, Math & Zodiac Riddles', 'easy', 'How many "Earthly Branches" must pass before the Horse returns?', '5', '12', '24', '60', '12', NULL),
(132, 'Logic, Math & Zodiac Riddles', 'medium', 'If 2026 is a "Yang" year, what was 2025?', 'Yang', 'Yin', 'Neutral', 'Fire', 'Yin', NULL),
(133, 'Logic, Math & Zodiac Riddles', 'easy', 'Which of these is a "Horse" word for a person who is unlikely to win but does?', 'Fast Horse', 'Dark Horse', 'White Horse', 'Red Horse', 'Dark Horse', NULL),
(134, 'Logic, Math & Zodiac Riddles', 'easy', 'In a 12-year cycle, what is the 12th animal?', 'Dog', 'Pig', 'Rat', 'Rooster', 'Pig', NULL),
(135, 'Logic, Math & Zodiac Riddles', 'hard', 'What color do you get if you mix the "Fire" of 2026 (Red) with the "Wood" that feeds it (Green)?', 'Blue', 'Yellow/Brown', 'Purple', 'Pink', 'Yellow/Brown', NULL),
(136, 'Logic, Math & Zodiac Riddles', 'medium', 'If you have 3 horses and you take away 2, how many horses do you have?', '1', '2', '3', '0', '2', NULL),
(137, 'Logic, Math & Zodiac Riddles', 'medium', 'The Horse is the 7th sign. Which sign is exactly 180 degrees opposite?', 'The 1st (Rat)', 'The 6th (Snake)', 'The 12th (Pig)', 'The 4th (Rabbit)', 'The 1st (Rat)', NULL),
(138, 'Logic, Math & Zodiac Riddles', 'easy', 'Which Chinese festival occurs on the 15th day of the New Year?', 'Dragon Boat', 'Lantern Festival', 'Mid-Autumn', 'Qingming', 'Lantern Festival', NULL),
(139, 'Logic, Math & Zodiac Riddles', 'hard', 'A "Fire Horse" year occurs when the Stem is "Bing" and the Branch is "Wu." How many combinations are there total?', '12', '24', '60', '120', '60', NULL),
(140, 'Logic, Math & Zodiac Riddles', 'medium', 'Which of these is a "Horse" constellation?', 'Pegasus', 'Orion', 'Ursa Major', 'Cassiopeia', 'Pegasus', NULL),
(141, 'Logic, Math & Zodiac Riddles', 'easy', 'If a Horse travels 20 miles per hour, how long does it take to run 10 miles?', '20 mins', '30 mins', '40 mins', '60 mins', '30 mins', NULL),
(142, 'Logic, Math & Zodiac Riddles', 'hard', 'In the "Great Race," which animal used a Horse''s help but didn''t thank it?', 'Rat', 'Snake', 'Monkey', 'Bee', 'Snake', NULL),
(143, 'Logic, Math & Zodiac Riddles', 'medium', 'How many "Trigrams" are in the Bagua (used in 2026 Feng Shui)?', '4', '6', '8', '12', '8', NULL),
(144, 'Logic, Math & Zodiac Riddles', 'easy', 'Which animal "clashes" with the Horse the most?', 'Rat', 'Ox', 'Tiger', 'Dragon', 'Rat', NULL),
(145, 'Logic, Math & Zodiac Riddles', 'hard', 'Which of these is the Horse''s "Lucky Day" of the month?', '2nd and 6th', '5th and 20th', '1st and 15th', '10th and 30th', '2nd and 6th', NULL),
(146, 'Logic, Math & Zodiac Riddles', 'easy', 'What is the "Fire Horse" known for in terms of speed?', 'Slow/Steady', 'Fast/Impulsive', 'Only runs at night', 'Doesn''t run', 'Fast/Impulsive', NULL),
(147, 'Logic, Math & Zodiac Riddles', 'medium', 'Which direction is associated with "Water" (The Horse''s opposite)?', 'North', 'South', 'East', 'West', 'North', NULL),
(148, 'Logic, Math & Zodiac Riddles', 'easy', 'How many years are in a "Small Cycle" of the Zodiac?', '1', '5', '12', '60', '12', NULL),
(149, 'Logic, Math & Zodiac Riddles', 'easy', 'Which of these "Horse" items is lucky to hang over a door?', 'Saddle', 'Horseshoe', 'Bridle', 'Stirrup', 'Horseshoe', NULL),
(150, 'Logic, Math & Zodiac Riddles', 'medium', 'To be a "Top 10" player, you need speed. What animal represents "Swiftness" alongside the Horse?', 'Rabbit', 'Snail', 'Ox', 'Pig', 'Rabbit', NULL);

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(151, 'Biological & Scientific Facts', 'hard', 'How many degrees of vision does a horse have due to the placement of its eyes?', '90°', '180°', '270°', 'nearly 360°', 'nearly 360°', NULL),
(152, 'Biological & Scientific Facts', 'medium', 'What is the only "blind spot" for a horse''s vision?', 'Directly behind them', 'Directly in front of their nose', 'To the left', 'To the right', 'Directly in front of their nose', NULL),
(153, 'Biological & Scientific Facts', 'medium', 'Can horses breathe through their mouths?', 'Yes', 'No - only through the nose', 'Only when running', 'Only when sleeping', 'No - only through the nose', NULL),
(154, 'Biological & Scientific Facts', 'medium', 'What is a "hand" in horse measurement equal to?', '2 inches', '4 inches', '6 inches', '10 inches', '4 inches', NULL),
(155, 'Biological & Scientific Facts', 'hard', 'How many bones does a horse typically have?', '105', '155', '205', '305', '205', NULL),
(156, 'Biological & Scientific Facts', 'medium', 'What is the fastest recorded sprinting speed of a horse?', '35 mph', '44 mph', '55 mph', '70 mph', '44 mph', NULL),
(157, 'Biological & Scientific Facts', 'medium', 'A horse''s hoof is made of the same protein as human hair and nails. What is it?', 'Calcium', 'Keratin', 'Collagen', 'Fibroin', 'Keratin', NULL),
(158, 'Biological & Scientific Facts', 'easy', 'Which of these is NOT a natural gait (way of walking) for a horse?', 'Trot', 'Canter', 'Gallop', 'Slither', 'Slither', NULL),
(159, 'Biological & Scientific Facts', 'medium', 'How many heart chambers does a horse have?', '2', '3', '4', '5', '4', NULL),
(160, 'Biological & Scientific Facts', 'easy', 'Horses are "herbivores." What does this mean?', 'They eat meat', 'They eat plants', 'They eat everything', 'They only eat grain', 'They eat plants', NULL),
(161, 'Biological & Scientific Facts', 'medium', 'What is the average lifespan of a domestic horse?', '10-15 years', '25-30 years', '40-50 years', '60-70 years', '25-30 years', NULL),
(162, 'Biological & Scientific Facts', 'hard', 'How many muscles are in each of a horse''s ears?', '4', '10', '16', '32', '10', NULL),
(163, 'Biological & Scientific Facts', 'easy', 'Which of these is a horse''s favorite treat for a boost of "Fire" energy?', 'Apples', 'Potatoes', 'Onions', 'Chocolate', 'Apples', NULL),
(164, 'Biological & Scientific Facts', 'medium', 'What is the largest organ in a horse''s body?', 'Heart', 'Lungs', 'Skin', 'Liver', 'Skin', NULL),
(165, 'Biological & Scientific Facts', 'medium', 'What is a "Bay" horse color?', 'All Black', 'Red-brown with black mane/tail', 'Grey with spots', 'Pure White', 'Red-brown with black mane/tail', NULL),
(166, 'Biological & Scientific Facts', 'medium', 'Do horses have a collarbone?', 'Yes', 'No', 'Only males', 'Only females', 'No', NULL),
(167, 'Biological & Scientific Facts', 'hard', 'What is the "frog" on a horse?', 'A parasite', 'Part of the hoof', 'A small muscle', 'A piece of equipment', 'Part of the hoof', NULL),
(168, 'Biological & Scientific Facts', 'medium', 'How long is a mare''s pregnancy (gestation period)?', '5 months', '9 months', '11 months', '14 months', '11 months', NULL),
(169, 'Biological & Scientific Facts', 'medium', 'Which horse breed is the most popular in the world?', 'Arabian', 'American Quarter Horse', 'Thoroughbred', 'Appaloosa', 'American Quarter Horse', NULL),
(170, 'Biological & Scientific Facts', 'easy', 'Horses are "social animals." What is a group of horses called?', 'A pack', 'A herd', 'A flock', 'A swarm', 'A herd', NULL),
(171, 'Biological & Scientific Facts', 'hard', 'What is the maximum number of "Fire Horses" that can be in one 12-year cycle?', '1', '2', '5', '12', '1', NULL),
(172, 'Biological & Scientific Facts', 'medium', 'What is the "withers" on a horse?', 'The tail', 'The highest point of the shoulders', 'The knee', 'The ear', 'The highest point of the shoulders', NULL),
(173, 'Biological & Scientific Facts', 'medium', 'How many gallons of water does a horse drink per day?', '1-2', '5-10', '20-30', '50-60', '5-10', NULL),
(174, 'Biological & Scientific Facts', 'medium', 'At what age is a horse considered "senior"?', '10', '15', '20', '30', '15', NULL),
(175, 'Biological & Scientific Facts', 'medium', 'Which of these senses is the most developed in a horse?', 'Smell', 'Hearing', 'Touch', 'Sight', 'Hearing', NULL),
(176, 'Historical War Horses', 'medium', 'What was the name of Alexander the Great''s famous horse?', 'Pegasus', 'Bucephalus', 'Marengo', 'Copenhagen', 'Bucephalus', NULL),
(177, 'Historical War Horses', 'medium', 'Which famous General rode a horse named "Marengo" at the Battle of Waterloo?', 'Washington', 'Napoleon', 'Caesar', 'Wellington', 'Napoleon', NULL),
(178, 'Historical War Horses', 'medium', 'What color was Napoleon''s horse "Marengo"?', 'Black', 'White/Grey', 'Brown', 'Spotted', 'White/Grey', NULL),
(179, 'Historical War Horses', 'medium', 'In the US Civil War, what was the name of General Robert E. Lee''s horse?', 'Traveler', 'Scout', 'Bandit', 'Freedom', 'Traveler', NULL),
(180, 'Historical War Horses', 'hard', 'Which ancient civilization is credited with inventing the chariot?', 'Romans', 'Greeks', 'Hittites/Sumerians', 'Chinese', 'Hittites/Sumerians', NULL),
(181, 'Historical War Horses', 'hard', 'The "Pony Express" was a mail service. How long did it actually last?', '18 months', '5 years', '10 years', '20 years', '18 months', NULL),
(182, 'Historical War Horses', 'medium', 'Who was the legendary "Lady" who rode a horse through Coventry naked?', 'Lady Macbeth', 'Lady Godiva', 'Lady Guinevere', 'Lady Marian', 'Lady Godiva', NULL),
(183, 'Historical War Horses', 'medium', 'Which famous horse won the Triple Crown in 1973 with record speeds?', 'Secretariat', 'Red Rum', 'Seabiscuit', 'Man o'' War', 'Secretariat', NULL),
(184, 'Historical War Horses', 'medium', 'In the 13th century, which Empire relied most heavily on mounted archers?', 'Roman', 'Mongol', 'Ottoman', 'British', 'Mongol', NULL),
(185, 'Historical War Horses', 'hard', 'What is the name of the "Ghost Horse" in American folklore?', 'Silver', 'The White Steed of the Prairies', 'Phantom', 'Shadow', 'The White Steed of the Prairies', NULL),
(186, 'Historical War Horses', 'hard', 'Which US President was a champion horseman and died of a throat infection after a ride?', 'Lincoln', 'Washington', 'Jefferson', 'Roosevelt', 'Washington', NULL),
(187, 'Historical War Horses', 'hard', 'What was the first animal to be domesticated for transport?', 'Horse', 'Donkey', 'Camel', 'Elephant', 'Donkey', NULL),
(188, 'Historical War Horses', 'hard', 'In World War I, how many horses are estimated to have died?', '100,000', '1 million', '8 million', '20 million', '8 million', NULL),
(189, 'Historical War Horses', 'medium', 'Which "Horse" culture lived in the Great Plains of North America?', 'Aztecs', 'Mayans', 'Comanches', 'Incas', 'Comanches', NULL),
(190, 'Historical War Horses', 'easy', 'What is the "Cavalry"?', 'Foot soldiers', 'Soldiers on horses', 'Sailors', 'Pilots', 'Soldiers on horses', NULL),
(191, 'Historical War Horses', 'easy', 'In 2026, the "South" direction belongs to the Horse. What is the traditional "Fire" season?', 'Winter', 'Spring', 'Summer', 'Autumn', 'Summer', NULL),
(192, 'Historical War Horses', 'hard', 'Which legendary Chinese archer is often depicted on a horse?', 'Hou Yi', 'Li Guang', 'Mulan', 'Yue Fei', 'Li Guang', NULL),
(193, 'Historical War Horses', 'medium', 'What is the "Year of the Horse" called in Japanese?', 'Uma-doshi', 'Inu-doshi', 'Tatsu-doshi', 'Ne-doshi', 'Uma-doshi', NULL),
(194, 'Historical War Horses', 'hard', 'The "Terracotta Army" includes how many life-sized clay horses?', '12', '150', '520', '2000', '520', NULL),
(195, 'Historical War Horses', 'medium', 'Which of these is a "Horse" weapon used by knights?', 'Lance', 'Rapier', 'Katana', 'Bo Staff', 'Lance', NULL),
(196, 'Historical War Horses', 'medium', 'What is the name of the horse in the 2026 CNY logo (standardized by many designers)?', 'Spirit', 'The Fire Steed', 'Lucky', 'Flame', 'The Fire Steed', NULL),
(197, 'Historical War Horses', 'medium', 'Which famous explorer brought horses back to the Americas in 1493?', 'Marco Polo', 'Columbus', 'Magellan', 'Cook', 'Columbus', NULL),
(198, 'Historical War Horses', 'medium', 'What does a "Red Horse" symbolize in many cultures?', 'Peace', 'War/Passion', 'Death', 'Wealth', 'War/Passion', NULL),
(199, 'Historical War Horses', 'medium', 'How many miles can a fit horse travel in a single day?', '10', '30', '50', '100', '30', NULL),
(200, 'Historical War Horses', 'easy', 'Which famous Mongol leader was known for his skilled cavalry and horses that conquered much of Asia?', 'Kublai Khan', 'Genghis Khan', 'Attila the Hun', 'Alexander the Great', 'Genghis Khan', 'Genghis Khan built the largest contiguous land empire in history, largely due to his legendary Mongol cavalry and horses.');

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(201, 'Horse Equipment & Sports', 'medium', 'What is the name of the metal bit that goes inside a horse''s mouth to guide it?', 'Stirrup', 'Girth', 'Bit', 'Pommel', 'Bit', NULL),
(202, 'Horse Equipment & Sports', 'easy', 'Which piece of equipment do you put your feet in while riding?', 'Reins', 'Stirrups', 'Halter', 'Saddlebag', 'Stirrups', NULL),
(203, 'Horse Equipment & Sports', 'medium', 'What is a "Girth" used for?', 'Cleaning hooves', 'Securing the saddle', 'Feeding the horse', 'Protecting ears', 'Securing the saddle', NULL),
(204, 'Horse Equipment & Sports', 'medium', 'In which Olympic event does a horse "dance" to music?', 'Show Jumping', 'Eventing', 'Dressage', 'Steeplechase', 'Dressage', NULL),
(205, 'Horse Equipment & Sports', 'hard', 'What is the standard length of a horse race "Furlong"?', '100 yards', '220 yards', '500 yards', '1 mile', '220 yards', NULL),
(206, 'Horse Equipment & Sports', 'medium', 'Which of these is a "Western" style saddle feature that "English" saddles lack?', 'Seat', 'Horn', 'Cantle', 'Flap', 'Horn', NULL),
(207, 'Horse Equipment & Sports', 'medium', 'What is "Longeing" a horse?', 'Brushing its hair', 'Making it run in a circle on a long rope', 'Feeding it', 'Putting on shoes', 'Making it run in a circle on a long rope', NULL),
(208, 'Horse Equipment & Sports', 'hard', 'How many hurdles are in a standard Olympic Show Jumping round?', '5-8', '12-15', '20-25', '30-35', '12-15', NULL),
(209, 'Horse Equipment & Sports', 'medium', 'What color jacket do elite show jumpers traditionally wear?', 'Red', 'Blue', 'Green', 'Yellow', 'Red', NULL),
(210, 'Horse Equipment & Sports', 'medium', 'In the sport of Polo, how many players are on each team?', '2', '4', '6', '8', '4', NULL),
(211, 'Horse Equipment & Sports', 'medium', 'What do you call a person who fits shoes onto a horse?', 'Cobbler', 'Farrier', 'Groomer', 'Jockey', 'Farrier', NULL),
(212, 'Horse Equipment & Sports', 'medium', 'Which of these is the most prestigious horse race in the UK?', 'The Royal Ascot', 'The Kentucky Derby', 'The Melbourne Cup', 'The Prix de l''Arc', 'The Royal Ascot', NULL),
(213, 'Horse Equipment & Sports', 'hard', 'What is a "Martingale" used for?', 'Keeping a horse''s head down', 'Protecting legs', 'Cleaning the coat', 'Measuring height', 'Keeping a horse''s head down', NULL),
(214, 'Horse Equipment & Sports', 'medium', 'In horse racing, what is the "Triple Crown"?', '3 races in 3 days', '3 specific races for 3-year-olds', '3 wins by 1 jockey', '3 different tracks', '3 specific races for 3-year-olds', NULL),
(215, 'Horse Equipment & Sports', 'medium', 'What is a "Pony"?', 'A baby horse', 'A horse under 14.2 hands', 'A sick horse', 'A wild horse', 'A horse under 14.2 hands', NULL),
(216, 'Horse Equipment & Sports', 'easy', 'What are "Reins" attached to?', 'The saddle', 'The bit/bridle', 'The tail', 'The stirrups', 'The bit/bridle', NULL),
(217, 'Horse Equipment & Sports', 'medium', 'Which of these is a grooming tool used to remove mud?', 'Curry Comb', 'Toothbrush', 'Silk cloth', 'Sandpaper', 'Curry Comb', NULL),
(218, 'Horse Equipment & Sports', 'hard', 'What is "Vaulting"?', 'Jumping over fences', 'Gymnastics on a moving horse', 'Racing uphill', 'Pulling a carriage', 'Gymnastics on a moving horse', NULL),
(219, 'Horse Equipment & Sports', 'medium', 'How often should a horse''s hooves be trimmed?', 'Once a year', 'Every 6-8 weeks', 'Every day', 'Every 6 months', 'Every 6-8 weeks', NULL),
(220, 'Horse Equipment & Sports', 'medium', 'What is the "Paddock"?', 'The horse''s bed', 'An enclosed field for exercise', 'A type of food', 'The jockey''s locker', 'An enclosed field for exercise', NULL),
(221, 'Horse Equipment & Sports', 'hard', 'In 2026, the Fire Horse is energetic. Which sport requires the MOST stamina?', 'Endurance Riding', 'Show Jumping', 'Dressage', 'Vaulting', 'Endurance Riding', NULL),
(222, 'Horse Equipment & Sports', 'medium', 'What is a "Blaze" on a horse?', 'A type of fire', 'A white stripe down the face', 'A fast gallop', 'A brand mark', 'A white stripe down the face', NULL),
(223, 'Horse Equipment & Sports', 'medium', 'Which breed is famous for its "natural" jumping ability and speed?', 'Thoroughbred', 'Clydesdale', 'Shetland', 'Donkey', 'Thoroughbred', NULL),
(224, 'Horse Equipment & Sports', 'easy', 'What is a "Hack"?', 'A computer virus', 'A casual ride for pleasure', 'A horse''s cough', 'A racing move', 'A casual ride for pleasure', NULL),
(225, 'Horse Equipment & Sports', 'easy', 'What does "Tack" refer to?', 'Small nails', 'Horse equipment/gear', 'The horse''s speed', 'The stable floor', 'Horse equipment/gear', NULL),
(226, 'The Five Elements', 'medium', 'In 2026, Fire is the element. Which element "Destroys" Fire in the cycle?', 'Wood', 'Earth', 'Water', 'Metal', 'Water', NULL),
(227, 'The Five Elements', 'medium', 'Which element "Produces" the Fire of the 2026 Horse?', 'Earth', 'Metal', 'Water', 'Wood', 'Wood', NULL),
(228, 'The Five Elements', 'medium', 'Fire "Destroys" which element?', 'Wood', 'Metal', 'Earth', 'Water', 'Metal', NULL),
(229, 'The Five Elements', 'medium', 'Fire "Produces" which element (as ash)?', 'Wood', 'Water', 'Earth', 'Metal', 'Earth', NULL),
(230, 'The Five Elements', 'easy', 'Which of these colors represents the "Earth" element?', 'Red', 'Black', 'Yellow/Brown', 'Green', 'Yellow/Brown', NULL),
(231, 'The Five Elements', 'hard', 'If 2026 is Fire, what element was the Horse in 2014?', 'Water', 'Wood', 'Metal', 'Earth', 'Wood', NULL),
(232, 'The Five Elements', 'easy', 'How many elements are in the Chinese system?', '3', '4', '5', '6', '5', NULL),
(233, 'The Five Elements', 'medium', 'Which of these is NOT one of the 5 elements?', 'Air', 'Metal', 'Wood', 'Water', 'Air', NULL),
(234, 'The Five Elements', 'hard', 'What is the "Heavenly Stem" for 2026?', 'Jia', 'Yi', 'Bing', 'Ding', 'Bing', NULL),
(235, 'The Five Elements', 'hard', 'Bing (Yang Fire) is often compared to what natural object?', 'A candle', 'The Sun', 'A forest fire', 'A spark', 'The Sun', NULL),
(236, 'The Five Elements', 'hard', 'What is the "Earthly Branch" name for the Horse?', 'Chen', 'Si', 'Wu', 'Wei', 'Wu', NULL),
(237, 'The Five Elements', 'hard', 'The Fire Horse is "Double Fire" because the Horse''s fixed element is Fire. What does this mean?', 'Very calm', 'Extremely intense', 'Very cold', 'Twice as slow', 'Extremely intense', NULL),
(238, 'The Five Elements', 'medium', 'Which season does the "Metal" element represent?', 'Spring', 'Summer', 'Autumn', 'Winter', 'Autumn', NULL),
(239, 'The Five Elements', 'medium', 'Which season does the "Wood" element represent?', 'Spring', 'Summer', 'Autumn', 'Winter', 'Spring', NULL),
(240, 'The Five Elements', 'medium', 'Which animal is the "Water" equivalent of the Horse (opposite on the wheel)?', 'Rat', 'Pig', 'Ox', 'Snake', 'Rat', NULL),
(241, 'The Five Elements', 'medium', 'In 2026, the Fire element is "Yang." What are the characteristics of Yang?', 'Internal/Soft', 'External/Hard', 'Dark/Cold', 'Still/Quiet', 'External/Hard', NULL),
(242, 'The Five Elements', 'hard', 'Which element is associated with the planet Mars?', 'Metal', 'Water', 'Wood', 'Fire', 'Fire', NULL),
(243, 'The Five Elements', 'hard', 'Which element is associated with the planet Venus?', 'Fire', 'Earth', 'Metal', 'Water', 'Metal', NULL),
(244, 'The Five Elements', 'hard', 'Which element is associated with the planet Jupiter?', 'Wood', 'Metal', 'Earth', 'Water', 'Wood', NULL),
(245, 'The Five Elements', 'hard', 'Which element is associated with the planet Mercury?', 'Metal', 'Wood', 'Water', 'Earth', 'Water', NULL),
(246, 'The Five Elements', 'hard', 'Which element is associated with the planet Saturn?', 'Fire', 'Earth', 'Wood', 'Metal', 'Earth', NULL),
(247, 'The Five Elements', 'hard', 'In 2026, which direction is considered "unlucky" for renovation (The Three Killings)?', 'South', 'North', 'East', 'West', 'North', NULL),
(248, 'The Five Elements', 'easy', 'How many years does it take for a "Fire Horse" to return?', '12', '60', '100', '120', '60', NULL),
(249, 'The Five Elements', 'medium', 'Which of these animals belongs to the "Fire" element group?', 'Tiger', 'Horse', 'Dog', 'All of them', 'All of them', NULL),
(250, 'The Five Elements', 'easy', 'In the Five Elements cycle, which element is said to "control" or overcome Fire?', 'Wood', 'Earth', 'Metal', 'Water', 'Water', 'Water extinguishes Fire in the controlling/overcoming cycle of the Five Elements.');

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(251, 'Horse Idioms & Phrases', 'easy', 'What does it mean to "eat like a horse"?', 'Eat very little', 'Eat very quickly', 'Eat a large amount', 'Eat only grass', 'Eat a large amount', NULL),
(252, 'Horse Idioms & Phrases', 'easy', 'If someone tells you to "hold your horses," what are they asking you to do?', 'Stop moving', 'Be patient/Wait', 'Buy a horse', 'Hold a rope', 'Be patient/Wait', NULL),
(253, 'Horse Idioms & Phrases', 'easy', 'What is a "one-horse town"?', 'A town with a race track', 'A small/unimportant place', 'A town with no cars', 'A wealthy town', 'A small/unimportant place', NULL),
(254, 'Horse Idioms & Phrases', 'easy', 'If you are "back in the saddle," what are you doing?', 'Going to sleep', 'Returning to an activity', 'Falling down', 'Buying new clothes', 'Returning to an activity', NULL),
(255, 'Horse Idioms & Phrases', 'medium', 'What does the idiom "don''t look a gift horse in the mouth" mean?', 'Don''t be ungrateful for a gift', 'Horses have bad teeth', 'Gifts are dangerous', 'Check for quality', 'Don''t be ungrateful for a gift', NULL),
(256, 'Horse Idioms & Phrases', 'medium', 'In the phrase "flogging a dead horse," what is the person doing?', 'Cleaning', 'Wasting effort on something hopeless', 'Exercising', 'Winning', 'Wasting effort on something hopeless', NULL),
(257, 'Horse Idioms & Phrases', 'easy', 'What is a "dark horse" in a competition?', 'An angry player', 'A black horse', 'An unexpected winner', 'A player who cheats', 'An unexpected winner', NULL),
(258, 'Horse Idioms & Phrases', 'medium', 'If you "get off your high horse," what are you doing?', 'Dismounting', 'Stopping being arrogant', 'Jumping', 'Selling your horse', 'Stopping being arrogant', NULL),
(259, 'Horse Idioms & Phrases', 'medium', 'What does it mean to "put the cart before the horse"?', 'To be very fast', 'To do things in the wrong order', 'To be very strong', 'To prepare for travel', 'To do things in the wrong order', NULL),
(260, 'Horse Idioms & Phrases', 'medium', 'What does the Chinese idiom "Ma Ma Hu Hu" (Horse Horse Tiger Tiger) mean?', 'Very brave', 'So-so / Mediocre', 'Very fast', 'Dangerous', 'So-so / Mediocre', NULL),
(261, 'Horse Idioms & Phrases', 'medium', 'If someone is "champing at the bit," how do they feel?', 'Hungry', 'Eager/Impatient', 'Tired', 'Sad', 'Eager/Impatient', NULL),
(262, 'Horse Idioms & Phrases', 'medium', 'What is a "horse of a different color"?', 'A miracle', 'A completely different matter', 'A beautiful painting', 'A new friend', 'A completely different matter', NULL),
(263, 'Horse Idioms & Phrases', 'easy', 'To "work like a horse" means to:', 'Work outdoors', 'Work very hard', 'Work for no pay', 'Work with animals', 'Work very hard', NULL),
(264, 'Horse Idioms & Phrases', 'hard', 'What is a "stalking horse"?', 'A hunting horse', 'A false pretext to hide a real plan', 'A tall horse', 'A fast runner', 'A false pretext to hide a real plan', NULL),
(265, 'Horse Idioms & Phrases', 'medium', 'In Australia, "The race that stops a nation" refers to which horse race?', 'The Derby', 'The Melbourne Cup', 'The Sydney Stakes', 'The Outback Run', 'The Melbourne Cup', NULL),
(266, 'Horse Idioms & Phrases', 'medium', 'What does "beat a dead horse" mean?', 'To keep fighting', 'To waste time on a settled issue', 'To win easily', 'To hunt', 'To waste time on a settled issue', NULL),
(267, 'Horse Idioms & Phrases', 'hard', 'If you "change horses in midstream," what are you doing?', 'Swimming', 'Changing your plan/leader at a bad time', 'Getting wet', 'Winning', 'Changing your plan/leader at a bad time', NULL),
(268, 'Horse Idioms & Phrases', 'easy', 'What does "horse sense" mean?', 'Smelling a horse', 'Common sense', 'Ability to ride', 'Good hearing', 'Common sense', NULL),
(269, 'Horse Idioms & Phrases', 'easy', 'What is "horseplay"?', 'Playing with a pony', 'Rough or boisterous play', 'A theater show', 'Betting', 'Rough or boisterous play', NULL),
(270, 'Horse Idioms & Phrases', 'medium', 'To "ride roughshod" over someone means to:', 'Give them a ride', 'Act without considering their feelings', 'Race them', 'Help them', 'Act without considering their feelings', NULL),
(271, 'Horse Idioms & Phrases', 'hard', 'In military terms, what is a "Hobby Horse"?', 'A small horse', 'A favorite topic or obsession', 'A toy', 'A training tool', 'A favorite topic or obsession', NULL),
(272, 'Horse Idioms & Phrases', 'medium', 'What does the idiom "you can lead a horse to water, but you can''t make it drink" mean?', 'Horses are stubborn', 'You can''t force someone to accept help', 'Water is important', 'Keep trying', 'You can''t force someone to accept help', NULL),
(273, 'Horse Idioms & Phrases', 'hard', 'What is "charity on horseback"?', 'Giving money', 'Help that comes too late or is insufficient', 'A parade', 'A race for a cause', 'Help that comes too late or is insufficient', NULL),
(274, 'Horse Idioms & Phrases', 'medium', 'If someone is "on their high horse," they are being:', 'Tall', 'Superior/Arrogant', 'Fast', 'Happy', 'Superior/Arrogant', NULL),
(275, 'Horse Idioms & Phrases', 'hard', 'What is a "Horse-Marine"?', 'A sea horse', 'Someone out of their element', 'A sailor', 'A soldier', 'Someone out of their element', NULL),
(276, 'Literature, Myth & Fantasy', 'easy', 'In the Odyssey, what was the "Trojan Horse" made of?', 'Stone', 'Bronze', 'Wood', 'Gold', 'Wood', NULL),
(277, 'Literature, Myth & Fantasy', 'easy', 'What is the name of the winged horse in Disney''s Hercules?', 'Icarus', 'Pegasus', 'Phil', 'Zeus', 'Pegasus', NULL),
(278, 'Literature, Myth & Fantasy', 'hard', 'In Gulliver''s Travels, what is the name of the race of intelligent horses?', 'Houyhnhnms', 'Yahoos', 'Lilliputians', 'Giants', 'Houyhnhnms', NULL),
(279, 'Literature, Myth & Fantasy', 'medium', 'Which famous book by Anna Sewell is "autobiography" of a horse?', 'War Horse', 'Black Beauty', 'National Velvet', 'Flicka', 'Black Beauty', NULL),
(280, 'Literature, Myth & Fantasy', 'medium', 'In The Lord of the Rings, who is the Lord of all Horses?', 'Arod', 'Bill', 'Shadowfax', 'Asfaloth', 'Shadowfax', NULL),
(281, 'Literature, Myth & Fantasy', 'medium', 'What color is the horse ridden by the "Headless Horseman" in The Legend of Sleepy Hollow?', 'White', 'Black', 'Brown', 'Grey', 'Black', NULL),
(282, 'Literature, Myth & Fantasy', 'medium', 'In Greek mythology, who is the god of the Sea and creator of horses?', 'Zeus', 'Hades', 'Poseidon', 'Apollo', 'Poseidon', NULL),
(283, 'Literature, Myth & Fantasy', 'medium', 'What is a "Kelpie" in Scottish folklore?', 'A sea monster', 'A shape-shifting water horse', 'A mountain pony', 'A fairy', 'A shape-shifting water horse', NULL),
(284, 'Literature, Myth & Fantasy', 'hard', 'In The Chronicles of Narnia, what is the name of the "Bree" the horse?', 'Breehy-hinny-brinny-hoohy-hah', 'Boxer', 'Shadow', 'Clover', 'Breehy-hinny-brinny-hoohy-hah', NULL),
(285, 'Literature, Myth & Fantasy', 'medium', 'What is the name of the workhorse in George Orwell''s Animal Farm?', 'Napoleon', 'Snowball', 'Boxer', 'Benjamin', 'Boxer', NULL),
(286, 'Literature, Myth & Fantasy', 'medium', 'In Norse myth, which Eight-legged horse belongs to Odin?', 'Fenrir', 'Sleipnir', 'Jormungand', 'Thor', 'Sleipnir', NULL),
(287, 'Literature, Myth & Fantasy', 'hard', 'Which fictional horse lived on "Puffin Island"?', 'Misty of Chincoteague', 'The Black Stallion', 'Flicka', 'Silver', 'Misty of Chincoteague', NULL),
(288, 'Literature, Myth & Fantasy', 'medium', 'In the Harry Potter world, what are the invisible horses that can only be seen by those who have witnessed death?', 'Hippogriffs', 'Thestrals', 'Centaurs', 'Unicorns', 'Thestrals', NULL),
(289, 'Literature, Myth & Fantasy', 'medium', 'Don Quixote''s horse was named...', 'Sancho', 'Dulcinea', 'Rocinante', 'Bucephalus', 'Rocinante', NULL),
(290, 'Literature, Myth & Fantasy', 'easy', 'What is a "Centaur"?', 'A horse with wings', 'A man with a horse''s body', 'A two-headed horse', 'A talking horse', 'A man with a horse''s body', NULL),
(291, 'Literature, Myth & Fantasy', 'medium', 'In the movie The NeverEnding Story, what is the name of Atreyu''s horse?', 'Artax', 'Falcor', 'Gmork', 'Morla', 'Artax', NULL),
(292, 'Literature, Myth & Fantasy', 'hard', 'Who wrote the play Equus?', 'Shakespeare', 'Peter Shaffer', 'Arthur Miller', 'Beckett', 'Peter Shaffer', NULL),
(293, 'Literature, Myth & Fantasy', 'hard', 'Which famous knight had a horse named Gringolet?', 'Lancelot', 'Gawain', 'Arthur', 'Galahad', 'Gawain', NULL),
(294, 'Literature, Myth & Fantasy', 'hard', 'In the poem The Highwayman, what is the horse''s gait described as?', 'Trotting', 'Galloping', 'Tlot-tlot', 'Cantering', 'Tlot-tlot', NULL),
(295, 'Literature, Myth & Fantasy', 'easy', 'Which "Fire Horse" element year would a character born in 1966 have?', 'Wood', 'Fire', 'Earth', 'Metal', 'Fire', NULL),
(296, 'Literature, Myth & Fantasy', 'hard', 'In Chinese mythology, the "Dragon Horse" is called...', 'Qilin', 'Longma', 'Pixiu', 'Fenghuang', 'Longma', NULL),
(297, 'Literature, Myth & Fantasy', 'medium', 'In Sleeping Beauty, what is the name of Prince Phillip''s horse?', 'Samson', 'Major', 'Angus', 'Philippe', 'Samson', NULL),
(298, 'Literature, Myth & Fantasy', 'hard', 'Which comic book hero has a horse named "Comet the Super-Horse"?', 'Superman', 'Supergirl', 'Batman', 'Wonder Woman', 'Supergirl', NULL),
(299, 'Literature, Myth & Fantasy', 'easy', 'What is the name of the horse in The Lone Ranger?', 'Scout', 'Silver', 'Trigger', 'Buttermilk', 'Silver', NULL),
(300, 'Literature, Myth & Fantasy', 'easy', 'In Chinese mythology, which celestial animal is often depicted as a guardian of treasure and wisdom?', 'Phoenix', 'Dragon', 'Qilin', 'Tortoise', 'Dragon', 'In Chinese mythology, the Dragon is the guardian of treasure, wisdom, and celestial power, often depicted protecting pearls and sacred objects.');

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(301, 'Pop Music & Sound', 'medium', 'Which artist released the 2024 album Cowboy Carter featuring "Horse" imagery?', 'Taylor Swift', 'Beyoncé', 'Miley Cyrus', 'Adele', 'Beyoncé', NULL),
(302, 'Pop Music & Sound', 'easy', 'In the song "Old Town Road," Lil Nas X says he has the horses in the...?', 'Front', 'Back', 'Stable', 'Trailer', 'Back', NULL),
(303, 'Pop Music & Sound', 'medium', 'Which rock band had a hit with the song "Wild Horses"?', 'The Beatles', 'The Rolling Stones', 'Led Zeppelin', 'The Who', 'The Rolling Stones', NULL),
(304, 'Pop Music & Sound', 'medium', 'America had a hit song about a "Horse with No..."?', 'Name', 'Tail', 'Rider', 'Shoes', 'Name', NULL),
(305, 'Pop Music & Sound', 'medium', 'Katy Perry''s song "Dark Horse" features a guest verse by which rapper?', 'Snoop Dogg', 'Juicy J', 'Kanye West', 'Drake', 'Juicy J', NULL),
(306, 'Pop Music & Sound', 'hard', 'Which classical composer wrote the "William Tell Overture" (the Lone Ranger theme)?', 'Rossini', 'Beethoven', 'Mozart', 'Wagner', 'Rossini', NULL),
(307, 'Pop Music & Sound', 'medium', 'In the song "Jingle Bells," how many horses pull the sleigh?', 'One', 'Two', 'Six', 'Eight', 'One', NULL),
(308, 'Pop Music & Sound', 'hard', 'Which singer is known for the song "Bring on the Lucie" and was a 1940 "Metal Horse"?', 'John Lennon', 'Elvis Presley', 'Bob Dylan', 'Ringo Starr', 'John Lennon', NULL),
(309, 'Pop Music & Sound', 'medium', '"A Horse Is a Horse, of course, of course" is the theme song to which 1960s TV show?', 'Mister Ed', 'Lassie', 'Flipper', 'Bonanza', 'Mister Ed', NULL),
(310, 'Pop Music & Sound', 'hard', 'Which pop star famously entered the 2013 AMAs on a giant mechanical white horse?', 'Lady Gaga', 'Pink', 'Rihanna', 'Madonna', 'Lady Gaga', NULL),
(311, 'Pop Music & Sound', 'hard', 'The "Tennessee Walker" is a horse breed. What is it famous for?', 'Running', 'Its unique "running walk" gait', 'Jumping', 'Swimming', 'Its unique "running walk" gait', NULL),
(312, 'Pop Music & Sound', 'easy', 'What is the sound a horse makes called?', 'Bark', 'Neigh/Whinny', 'Meow', 'Roar', 'Neigh/Whinny', NULL),
(313, 'Pop Music & Sound', 'hard', 'Which 1966 "Fire Horse" singer is the lead of the band Bush?', 'Gavin Rossdale', 'Kurt Cobain', 'Eddie Vedder', 'Chris Cornell', 'Gavin Rossdale', NULL),
(314, 'Pop Music & Sound', 'medium', 'In the song "A Horse with No Name," what was the desert like?', 'Hot and dry', 'Cold and wet', 'Perfect', 'The ground was dry', 'The ground was dry', NULL),
(315, 'Pop Music & Sound', 'medium', 'Which heavy metal band has a song called "The Four Horsemen"?', 'Iron Maiden', 'Metallica', 'Megadeth', 'Slayer', 'Metallica', NULL),
(316, 'Pop Music & Sound', 'medium', 'What is a "snort" from a horse usually a sign of?', 'Anger', 'Clearing the nose/Excitement', 'Hunger', 'Sleepiness', 'Clearing the nose/Excitement', NULL),
(317, 'Pop Music & Sound', 'hard', 'In the "Great Race," which animal did the Horse think was a fly at first?', 'The Bee', 'The Snake', 'The Rat', 'The Spider', 'The Snake', NULL),
(318, 'Pop Music & Sound', 'hard', 'Which 1966 "Fire Horse" is a famous Janet Jackson collaborator and producer?', 'Jimmy Jam', 'Teddy Riley', 'Timbaland', 'Pharrell', 'Jimmy Jam', NULL),
(319, 'Pop Music & Sound', 'medium', 'The "Appaloosa" horse is famous for what pattern?', 'Stripes', 'Spots', 'Solid Gold', 'Blue', 'Spots', NULL),
(320, 'Pop Music & Sound', 'medium', 'What musical instrument''s bow is traditionally made from horsehair?', 'Guitar', 'Violin', 'Flute', 'Drums', 'Violin', NULL),
(321, 'Pop Music & Sound', 'medium', 'Which artist has a song titled "Pony"?', 'Ginuwine', 'Usher', 'R. Kelly', 'Ne-Yo', 'Ginuwine', NULL),
(322, 'Pop Music & Sound', 'medium', 'In the "Year of the Horse," music is said to be...?', 'Slow and melodic', 'Loud and rhythmic', 'Silent', 'Electronic only', 'Loud and rhythmic', NULL),
(323, 'Pop Music & Sound', 'hard', 'Which 1966 Fire Horse is the drummer for the band "No Doubt"?', 'Adrian Young', 'Travis Barker', 'Dave Grohl', 'Chad Smith', 'Adrian Young', NULL),
(324, 'Pop Music & Sound', 'medium', 'What is a "Whinny" used for by a horse?', 'Warning', 'Social greeting/Locating others', 'Pain', 'Hunger', 'Social greeting/Locating others', NULL),
(325, 'Pop Music & Sound', 'easy', 'Which of these is a "Horse" dance move?', 'The Moonwalk', 'The Pony', 'The Floss', 'The Robot', 'The Pony', NULL),
(326, '2026 CNY Taboos & Superstitions', 'medium', 'Why shouldn''t you wash your hair on the first day of the 2026 New Year?', 'It''s bad for the hair', 'It washes away luck/wealth', 'It''s too cold', 'The water is needed for cooking', 'It washes away luck/wealth', NULL),
(327, '2026 CNY Taboos & Superstitions', 'hard', 'What should you avoid eating for breakfast on the first day of CNY?', 'Fruit', 'Porridge (Congee)', 'Eggs', 'Dumplings', 'Porridge (Congee)', NULL),
(328, '2026 CNY Taboos & Superstitions', 'easy', 'In 2026, which gift is considered lucky for a Fire Horse?', 'A green plant', 'Red home decor', 'A blue watch', 'A silver mirror', 'Red home decor', NULL),
(329, '2026 CNY Taboos & Superstitions', 'medium', 'What does "crying" on New Year''s Day supposedly bring?', 'Rain', 'A year of bad luck/sorrow', 'Good health', 'Money', 'A year of bad luck/sorrow', NULL),
(330, '2026 CNY Taboos & Superstitions', 'medium', 'Why are "Red Couplets" pasted on doors?', 'To show wealth', 'To guide guests', 'To protect the house from evil', 'To keep the door warm', 'To protect the house from evil', NULL),
(331, '2026 CNY Taboos & Superstitions', 'medium', 'Which direction is "The Grand Duke" (Tai Sui) in 2026?', 'North', 'South', 'East', 'West', 'South', NULL),
(332, '2026 CNY Taboos & Superstitions', 'medium', 'If you face the "Tai Sui" directly in 2026, it is considered...?', 'Very Lucky', 'Disrespectful/Bad Luck', 'Brave', 'Neutral', 'Disrespectful/Bad Luck', NULL),
(333, '2026 CNY Taboos & Superstitions', 'easy', 'What should you do with your house before the New Year starts?', 'Paint it red', 'Clean it thoroughly', 'Leave it messy', 'Lock all doors', 'Clean it thoroughly', NULL),
(334, '2026 CNY Taboos & Superstitions', 'easy', 'What does "Nian" (the monster) hate most?', 'Loud noises and red color', 'Water and wind', 'Silence', 'Dark places', 'Loud noises and red color', NULL),
(335, '2026 CNY Taboos & Superstitions', 'easy', 'Which number should you avoid in a "Hongbao" (Red Envelope) amount?', '4', '8', '9', '6', '4', NULL),
(336, '2026 CNY Taboos & Superstitions', 'medium', 'Why are oranges and tangerines displayed in homes?', 'They smell good', 'Their names sound like "Luck" and "Wealth"', 'They are the Horse''s favorite', 'For snacks', 'Their names sound like "Luck" and "Wealth"', NULL),
(337, '2026 CNY Taboos & Superstitions', 'hard', 'On which day of CNY is it "The Birthday of All Humans"?', 'Day 1', 'Day 3', 'Day 7', 'Day 15', 'Day 7', NULL),
(338, '2026 CNY Taboos & Superstitions', 'medium', 'What is the "Lucky Flower" for the Horse sign in 2026?', 'Lily', 'Jasmine', 'Marigold', 'Tulip', 'Jasmine', NULL),
(339, '2026 CNY Taboos & Superstitions', 'medium', 'If a Fire Horse wears "Red" in their own year, it is to...?', 'Look stylish', 'Ward off bad luck (Tai Sui)', 'Stay warm', 'Attract a partner', 'Ward off bad luck (Tai Sui)', NULL),
(340, '2026 CNY Taboos & Superstitions', 'medium', 'Which of these should NOT be used on New Year''s Day?', 'Spoons', 'Scissors/Knives', 'Chopsticks', 'Bowls', 'Scissors/Knives', NULL),
(341, '2026 CNY Taboos & Superstitions', 'medium', 'What does the word "Fu" (Luck) pasted upside down mean?', 'Luck is falling', 'Luck has arrived', 'Bad luck go away', 'No luck here', 'Luck has arrived', NULL),
(342, '2026 CNY Taboos & Superstitions', 'medium', 'Why do people stay up late on New Year''s Eve?', 'To watch TV', 'To give parents "long life"', 'To wait for the Horse', 'To eat more', 'To give parents "long life"', NULL),
(343, '2026 CNY Taboos & Superstitions', 'medium', 'What is the "God of Wealth" called?', 'Caishen', 'Mulan', 'Guan Yu', 'Jade Emperor', 'Caishen', NULL),
(344, '2026 CNY Taboos & Superstitions', 'easy', 'Which animal is the "Best Match" to help a Horse in 2026?', 'Tiger', 'Rat', 'Rooster', 'Monkey', 'Tiger', NULL),
(345, '2026 CNY Taboos & Superstitions', 'easy', 'What color of clothing is traditionally for funerals and avoided at CNY?', 'Red', 'Yellow', 'White/Black', 'Green', 'White/Black', NULL),
(346, '2026 CNY Taboos & Superstitions', 'hard', 'In 2026, the "Center" of the house is hit by the "Conflict Star." What should you put there?', 'A Fire', 'A Red Rug', 'A fountain', 'A heavy stone', 'A Red Rug', NULL),
(347, '2026 CNY Taboos & Superstitions', 'medium', 'What is the "Lucky Gemstone" for 2026?', 'Jade', 'Ruby', 'Sapphire', 'Emerald', 'Ruby', NULL),
(348, '2026 CNY Taboos & Superstitions', 'easy', 'How many days after the New Year is the "Lantern Festival"?', '3', '7', '10', '15', '15', NULL),
(349, '2026 CNY Taboos & Superstitions', 'easy', 'What is the traditional "Lucky Greeting" in Cantonese?', 'Ni Hao', 'Gong Hei Fat Choy', 'Sayonara', 'Aloha', 'Gong Hei Fat Choy', NULL),
(350, '2026 CNY Taboos & Superstitions', 'easy', 'Why is it considered bad luck to sweep the floor on Chinese New Year Day?', 'It wakes the ancestors', 'You sweep away good fortune', 'It angers the Kitchen God', 'Dust attracts evil spirits', 'You sweep away good fortune', 'Sweeping on CNY is taboo because you might accidentally sweep away the good luck and fortune that arrives with the new year.');

INSERT INTO party_questions (id, category, difficulty, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
(351, 'Grandmaster Zodiac & Math', 'hard', 'Which "Heavenly Stem" was associated with the Horse in the year 1906?', 'Jia', 'Yi', 'Bing', 'Ding', 'Bing', NULL),
(352, 'Grandmaster Zodiac & Math', 'medium', 'If a Fire Horse is born every 60 years, how many will occur in a 300-year period?', '3', '4', '5', '6', '5', NULL),
(353, 'Grandmaster Zodiac & Math', 'hard', 'Which animal occupies the "11th Hour" (7pm–9pm) in the Chinese 24-hour clock?', 'Rooster', 'Dog', 'Pig', 'Horse', 'Dog', NULL),
(354, 'Grandmaster Zodiac & Math', 'hard', 'The Horse is a "Yang" sign. Which of these is its "Yin" counterpart in the Fire element?', 'Snake', 'Goat', 'Dragon', 'Tiger', 'Snake', NULL),
(355, 'Grandmaster Zodiac & Math', 'medium', 'In the "Six Harmony" system, which animal is the Horse''s perfect partner?', 'Tiger', 'Dog', 'Sheep', 'Dragon', 'Sheep', NULL),
(356, 'Grandmaster Zodiac & Math', 'hard', '2026 is the year of the "Bing Wu." What does the character "Wu" literally represent in ancient scripts?', 'A spear', 'A pestle/noon', 'A running leg', 'A sun', 'A pestle/noon', NULL),
(357, 'Grandmaster Zodiac & Math', 'hard', 'If you are born on Feb 10, 2026, which zodiac sign are you?', 'Horse', 'Snake', 'Goat', 'Dragon', 'Snake', NULL),
(358, 'Grandmaster Zodiac & Math', 'hard', 'How many "Solar Terms" (Jie Qi) are there in a single Chinese calendar year?', '12', '24', '36', '48', '24', NULL),
(359, 'Grandmaster Zodiac & Math', 'hard', 'Which trigram on the I-Ching represents the "Pure Yang" of the Horse''s peak summer energy?', 'Li', 'Qian', 'Kun', 'Kan', 'Li', NULL),
(360, 'Grandmaster Zodiac & Math', 'medium', 'The "Fire Horse" is famously avoided in some cultures because the personality is considered too...?', 'Lazy', 'Rebellious/Strong', 'Sad', 'Quiet', 'Rebellious/Strong', NULL),
(361, 'Grandmaster Zodiac & Math', 'hard', 'Which of these is a "Double Horse" time?', 'Noon in June', 'Midnight in December', '6am in March', '6pm in September', 'Noon in June', NULL),
(362, 'Grandmaster Zodiac & Math', 'medium', 'Which planet''s orbit is roughly 12 years, matching the Zodiac cycle?', 'Mars', 'Jupiter', 'Saturn', 'Venus', 'Jupiter', NULL),
(363, 'Grandmaster Zodiac & Math', 'hard', 'In the 60-year cycle, what is the sequence number of the "Bing Wu" (Fire Horse)?', '1st', '23rd', '43rd', '60th', '43rd', NULL),
(364, 'Grandmaster Zodiac & Math', 'hard', 'Which animal is the "San Sha" (Three Killings) direction for 2026?', 'Rat', 'Ox', 'Pig', 'All three', 'All three', NULL),
(365, 'Grandmaster Zodiac & Math', 'hard', 'If a Horse travels 1,000 "Li" in a day, how many miles is that roughly?', '100', '310', '500', '1000', '310', NULL),
(366, 'Grandmaster Zodiac & Math', 'hard', 'What is the "Weight" of a Fire Horse according to Chinese "Bone Weight" Astrology?', 'It varies by birth time', 'Always 5.0', 'Always 2.1', 'It''s a secret', 'It varies by birth time', NULL),
(367, 'Grandmaster Zodiac & Math', 'medium', 'Which of these "Emotions" is linked to the Fire element of 2026?', 'Fear', 'Anger', 'Joy/Excitement', 'Worry', 'Joy/Excitement', NULL),
(368, 'Grandmaster Zodiac & Math', 'hard', 'In the "Great Race," which animal was the Horse''s biggest rival for speed?', 'Tiger', 'Rabbit', 'Dragon', 'Dog', 'Dragon', NULL),
(369, 'Grandmaster Zodiac & Math', 'hard', 'What is the "Lucky Direction" for wealth for the Horse in 2026?', 'Northwest', 'Southeast', 'West', 'Southwest', 'West', NULL),
(370, 'Grandmaster Zodiac & Math', 'hard', 'Which of these is the Horse''s "Vitality" star?', 'Tian Yi', 'Jiang Xing', 'Hua Gai', 'Yi Ma', 'Jiang Xing', NULL),
(371, 'Grandmaster Zodiac & Math', 'hard', 'What is the "Horse''s Shadow" animal?', 'The Rat', 'The Ox', 'The Snake', 'The Goat', 'The Goat', NULL),
(372, 'Grandmaster Zodiac & Math', 'hard', 'In 2026, the "Five Yellow" misfortune star is in which sector?', 'North', 'Northeast', 'South', 'West', 'Northeast', NULL),
(373, 'Grandmaster Zodiac & Math', 'medium', 'Which element is considered the "Mother" of Fire?', 'Earth', 'Wood', 'Water', 'Metal', 'Wood', NULL),
(374, 'Grandmaster Zodiac & Math', 'medium', 'Which element is considered the "Child" of Fire?', 'Wood', 'Earth', 'Metal', 'Water', 'Earth', NULL),
(375, 'Grandmaster Zodiac & Math', 'hard', 'How many days are in the Lunar Month of the Horse (June 2026)?', '28', '29', '30', '31', '30', NULL),
(376, 'Final Countdown & Future Lore', 'medium', 'When does the Year of the Fire Horse 2026 officially end?', 'Dec 31, 2026', 'Feb 5, 2027', 'Feb 17, 2027', 'Jan 1, 2027', 'Feb 5, 2027', NULL),
(377, 'Final Countdown & Future Lore', 'easy', 'Which animal will take over the leaderboard in 2027?', 'Goat/Sheep', 'Monkey', 'Rooster', 'Dog', 'Goat/Sheep', NULL),
(378, 'Final Countdown & Future Lore', 'medium', 'What element will the 2027 Goat be?', 'Wood', 'Fire', 'Earth', 'Water', 'Fire', NULL),
(379, 'Final Countdown & Future Lore', 'hard', 'The Horse is "Wu." What is the "Branch" of the Goat?', 'Wei', 'Shen', 'You', 'Xu', 'Wei', NULL),
(380, 'Final Countdown & Future Lore', 'hard', 'What is the "Fire Horse" spirit''s favorite drink (symbolically)?', 'Morning Dew', 'Wine', 'Salt Water', 'Tea', 'Morning Dew', NULL),
(381, 'Final Countdown & Future Lore', 'hard', 'Which of these is a famous "Horse" constellation in the Southern Hemisphere?', 'Centaurus', 'Equuleus', 'Pegasus', 'Monoceros', 'Centaurus', NULL),
(382, 'Final Countdown & Future Lore', 'hard', 'What is the smallest "Horse" constellation?', 'Pony', 'Equuleus', 'Little Dipper', 'Foal', 'Equuleus', NULL),
(383, 'Final Countdown & Future Lore', 'easy', 'In the "Great Race," who finished 12th?', 'Dog', 'Pig', 'Rooster', 'Monkey', 'Pig', NULL),
(384, 'Final Countdown & Future Lore', 'medium', 'Why did the Dog finish 11th despite being a good runner?', 'He was sleeping', 'He was playing in the water', 'He got lost', 'He was hungry', 'He was playing in the water', NULL),
(385, 'Final Countdown & Future Lore', 'easy', 'Which "Horse" animal is NOT in the Chinese Zodiac?', 'Zebra', 'Stallion', 'Pony', 'All are the same ''Horse'' sign', 'All are the same ''Horse'' sign', NULL),
(386, 'Final Countdown & Future Lore', 'medium', 'Which "Fire Horse" year was known for the start of the Cultural Revolution?', '1906', '1966', '2026', '1846', '1966', NULL),
(387, 'Final Countdown & Future Lore', 'easy', 'In 2026, what is the best "Red" item to carry for luck?', 'Red String', 'Red Wallet', 'Red Shirt', 'All of these', 'All of these', NULL),
(388, 'Final Countdown & Future Lore', 'hard', 'Which animal is the "Philosopher" of the Zodiac, often advising the Horse?', 'Snake', 'Rat', 'Monkey', 'Rooster', 'Snake', NULL),
(389, 'Final Countdown & Future Lore', 'hard', 'The Horse belongs to which "Cross"?', 'Cardinal', 'Fixed', 'Mutable', 'Equinox', 'Cardinal', NULL),
(390, 'Final Countdown & Future Lore', 'medium', 'What is the Horse''s "Power Color" to attract money in 2026?', 'Red', 'Gold', 'Green', 'Purple', 'Gold', NULL),
(391, 'Final Countdown & Future Lore', 'hard', 'How many total "Fire" animals are there in a 60-year cycle?', '5', '12', '10', '2', '12', NULL),
(392, 'Final Countdown & Future Lore', 'easy', 'Which of these is a "Horse" plant?', 'Horsetail', 'Horse Radish', 'Horse Chestnut', 'All of these', 'All of these', NULL),
(393, 'Final Countdown & Future Lore', 'medium', 'What does the "Horse" symbol represent in Buddhism?', 'Loyalty', 'Effort/Energy', 'Silence', 'Wealth', 'Effort/Energy', NULL),
(394, 'Final Countdown & Future Lore', 'medium', 'Which famous wall was built during many "Horse" years for defense?', 'Wall of Berlin', 'Great Wall of China', 'Hadrian''s Wall', 'Western Wall', 'Great Wall of China', NULL),
(395, 'Final Countdown & Future Lore', 'medium', 'In the "Great Race," who helped the Sheep and the Monkey cross the river?', 'The Horse', 'The Rooster', 'The Dragon', 'The Ox', 'The Rooster', NULL),
(396, 'Final Countdown & Future Lore', 'easy', 'What is the "Fire Horse" motto?', 'I think', 'I act', 'I free', 'I lead', 'I act', NULL),
(397, 'Final Countdown & Future Lore', 'hard', 'In 2026, which month is the "Clash Month" for the Horse?', 'June', 'December', 'March', 'September', 'December', NULL),
(398, 'Final Countdown & Future Lore', 'medium', 'Which of these is a "Horse" sport in the desert?', 'Polo', 'Endurance Racing', 'Dressage', 'Rodeo', 'Endurance Racing', NULL),
(399, 'Final Countdown & Future Lore', 'easy', 'What is the most important thing to have when playing this game?', 'Speed', 'Luck', 'Knowledge', 'A cool handle', 'A cool handle', NULL),
(400, 'Final Countdown & Future Lore', 'easy', '2026 is your year. Are you ready to run?', 'No', 'Maybe', 'Yes', 'I''m already winning', 'I''m already winning', NULL);

-- Verify the insert
SELECT COUNT(*) as total_questions FROM party_questions;
SELECT category, COUNT(*) as count FROM party_questions GROUP BY category ORDER BY category;
