import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Red Horse Oracle',
  description: 'Terms of Service for Red Horse Oracle - AI-generated entertainment product.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-gray-300 py-12 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Prominent Back Button at TOP */}
        <div className="mb-8">
          <a
            href="/"
            className="inline-flex items-center gap-2 bg-fire-gold hover:bg-yellow-500 text-black font-bold text-lg px-6 py-3 rounded-xl transition-all hover:scale-105 active:scale-95 shadow-lg"
          >
            <span className="text-xl">←</span>
            <span>Back to Home</span>
          </a>
        </div>

        <h1 className="text-3xl font-bold text-fire-gold mb-8">Terms of Service</h1>

        <p className="text-gray-500 mb-8">Last Updated: January 13, 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Service Description</h2>
            <p>
              Red Horse Oracle is a novelty entertainment product providing AI-generated digital
              artwork and storytelling based on Chinese zodiac and the Year of the Fire Horse 2026.
              The service generates personalized &quot;talismans&quot; containing lucky numbers, strategic
              mottos, or relationship advice based on user-provided birth dates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. No Guarantees</h2>
            <p>
              The &quot;Lucky Numbers,&quot; &quot;Strategies,&quot; &quot;Prophecies,&quot; and other content generated by Red
              Horse Oracle are created by an artificial intelligence algorithm. They are{' '}
              <strong className="text-red-400">
                not based on scientific fact, financial expertise, or guaranteed outcomes.
              </strong>{' '}
              Results are randomized and generated for entertainment purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Not Professional Advice</h2>
            <p>
              This service does not constitute financial, legal, medical, or gambling advice. Red
              Horse Oracle is not affiliated with any lottery, casino, or gambling institution.
              Users are solely responsible for their own actions and decisions. We strongly advise
              against using generated content as the basis for any financial or gambling decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Refund Policy</h2>
            <p>
              All sales are final. Due to the digital nature of the product and immediate
              generation upon purchase, refunds are not available. By completing a purchase, you
              acknowledge that you understand the entertainment-only nature of this product.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Age Requirement</h2>
            <p>
              Users must be 18 years of age or older to purchase from Red Horse Oracle. By making
              a purchase, you confirm that you meet this age requirement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Intellectual Property</h2>
            <p>
              Generated artwork is provided for personal use only. Users may share their generated
              talismans on social media with attribution to Red Horse Oracle. Commercial use of
              generated content is prohibited without written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Limitation of Liability</h2>
            <p>
              Red Horse Oracle and its operators shall not be liable for any direct, indirect,
              incidental, or consequential damages arising from the use of this service. This
              includes, but is not limited to, any losses incurred from gambling, investments, or
              other decisions made based on generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service
              after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Contact</h2>
            <p>
              For questions about these terms, please contact us at:{' '}
              <span className="text-fire-gold">support@redhorseoracle.com</span>
            </p>
          </section>
        </div>

        {/* Prominent Back Button at BOTTOM */}
        <div className="mt-12 pt-8 border-t border-gray-800">
          <a
            href="/"
            className="inline-flex items-center gap-2 bg-fire-gold hover:bg-yellow-500 text-black font-bold text-lg px-6 py-3 rounded-xl transition-all hover:scale-105 active:scale-95 shadow-lg"
          >
            <span className="text-xl">←</span>
            <span>Back to Home</span>
          </a>
        </div>
      </div>
    </main>
  );
}
